linebender/piet

piet-cairo/examples/basic-cairo.rs
piet-cairo/src/lib.rs

These aren't really usable yet as there is no way to get a `StrokeStyle` from the piet `RenderContext` generically yet.
I also had to add a context save/restore so that stroke styles for one path do not affect the styles of another.

Implement cairo stroke styles

---

piet-cairo/Cargo.toml
piet-cairo/examples/basic-cairo.rs
piet-cairo/src/lib.rs
piet-direct2d/Cargo.toml
piet-direct2d/examples/basic.rs
piet-direct2d/src/lib.rs
piet-web/Cargo.toml
piet-web/examples/basic/Cargo.toml
piet-web/examples/basic/src/lib.rs
piet-web/src/lib.rs
piet/Cargo.toml
piet/src/render_context.rs

This patch adds several fundamental methods to RenderContext and implementations to the three back-ends: clip, save/restore, and transform.

Add clip, transform, save/restore methods

---

Cargo.toml
piet-cairo/Cargo.toml
piet-cairo/examples/basic-cairo.rs
piet-cairo/src/lib.rs
piet-direct2d/Cargo.toml
piet-direct2d/examples/basic.rs
piet-direct2d/src/lib.rs
piet-test/Cargo.toml
piet-test/src/lib.rs
piet-web/examples/basic/Cargo.toml
piet-web/examples/basic/src/lib.rs
piet-web/src/lib.rs
piet/src/render_context.rs

Allow both owned and borrowed Shape parameters, following changes in kurbo.
Reduce duplication of test picture code by putting it in a separate crate. Over time, it is expected that crate will grow test and benchmark functionality, in addition to just being a repository of pictures.
Partially addresses #17

Refine Shape ownership; refactor test pictures

---

piet-cairo/src/lib.rs
piet-direct2d/Cargo.toml
piet-direct2d/src/lib.rs
piet-test/src/lib.rs
piet-test/src/picture_0.rs
piet-test/src/picture_2.rs
piet-web/Cargo.toml
piet-web/examples/basic/src/lib.rs
piet-web/src/lib.rs
piet/src/render_context.rs

This patch adds image capability, including support in all back-ends. Three image formats are intially supported; RGB 24 bits per pixel, and RGBA with both premultiplied and separate alpha. We will likely want to revisit this set, as some combinations of format and back-end may reduce the amount of conversion needed. In addition, there should be some mechanism (whether compile time or run time) to signal to drawing code which formats are most efficient. For example, premultiplied alpha is the most efficient on Cairo and Direct2D back ends, but separate alpha is dramatically more efficient on Web, as unpremultiplying requires 3 divides per pixel, and SIMD is not (at present) available.
The web implementation uses a scratch HTML Canvas to hold the image. That's most compatible when the …

Add images

---

Cargo.toml
piet-cairo/Cargo.toml
piet-common/Cargo.toml
piet-common/examples/png.rs
piet-common/src/cairo_back.rs
piet-common/src/direct2d_back.rs
piet-common/src/lib.rs
piet-direct2d/Cargo.toml
piet-direct2d/src/lib.rs
piet-test/Cargo.toml
piet/Cargo.toml

This patch creates a new piet-common crate that selects a default piet back-end, and also provides much of the boilerplate for setting it up so that a raw bitmap can be extracted.
The common crate currently works for direct2d and cairo back-ends. I might try to get a web back-end into this PR, or do it as a follow-on.
This PR also sets versions to 0.0.1 in preparation for the first crates.io release.

New crate for selecting default back-end

---

.travis.yml

This fixes travis errors, as it's gone missing on nightly.

Only install rustfmt on stable runs

---

piet/src/conv.rs

This adds a RoundFrom conversion from f32 to f64, which is especially
convenient when adapting existing code to use Cairo.
This is part of https://github.com/xi-editor/druid/issues/14

Add f32 -> f64 conversion

---

piet-cairo/Cargo.toml
piet-cairo/src/lib.rs
piet-common/Cargo.toml
piet-common/examples/png.rs
piet-direct2d/Cargo.toml
piet-direct2d/src/conv.rs
piet-direct2d/src/lib.rs
piet-test/Cargo.toml
piet-test/src/picture_0.rs
piet-test/src/picture_1.rs
piet-test/src/picture_3.rs
piet-test/src/picture_4.rs
piet-web/Cargo.toml
piet-web/examples/basic/Cargo.toml
piet-web/src/lib.rs
piet/src/lib.rs

This ensures that all of the piet family crates are depending on
a single version of kurbo, which is listed as a dependency in
exactly one `Cargo.toml`.
This was causing me a major headache when I wanted to test out some local changes I'd made to kurbo.
If there are any problems with this approach I'm curious to hear what they are, I couldn't think of anything.

Reexport kurbo from piet crate

---

piet-cairo/src/lib.rs
piet-common/examples/png.rs
piet-direct2d/src/conv.rs
piet-direct2d/src/lib.rs
piet-test/src/picture_0.rs
piet-test/src/picture_1.rs
piet-test/src/picture_2.rs
piet-test/src/picture_3.rs
piet-test/src/picture_4.rs
piet-web/src/lib.rs
piet/src/color.rs
piet/src/gradient.rs
piet/src/lib.rs
piet/src/render_context.rs

Use Color to represent colors

---

piet-common/src/lib.rs

The intention of this patch is to make it so that piet-common becomes
the only dependency necessary in order to get up and running with piet.
In addition, this improves documentation and cleans up the code that
selects the backend.
This is follow up on #52, and closes #54; I think this is a good enough solution.
I hope to do a batch of releases shortly after this lands, so that I can start cleaning up druid, using the new `Point` and `Size` types in kurbo.

Reexport piet and kurbo from piet-common

---

piet/src/color.rs

This lets us declare `const Color`s using these fns elsewhere.
I think these were `const` in an earlier version of this PR, but were maybe changed for symmetry with the float versions? I think it's worth having them be const even if the others can't be.

Make Color::rgba* constructors into const fns

---

piet-cairo/src/lib.rs
piet-direct2d/src/lib.rs
piet-web/src/lib.rs
piet/src/render_context.rs
piet/src/text.rs

This simplifies the implementation of various traits, by assuming
all points are `kurbo::Point`s, and all scalars are f64s.
Note: although it would be nice to delete `RoundFrom` and `RoundInto`, they are relied on fairly heavily in the d2d backend, so I've left them alone.
closes #61

Remove 'Point' and 'Coord' associated types

---

piet-cairo/src/lib.rs
piet-direct2d/src/lib.rs

This will be necessary to plumb a text layout context.
WIP, a similar change should be made for cairo and web impls.

Add a `new` method to d2d text

---

piet-cairo/src/lib.rs

For layout purposes, we want the x advance of the text, rather than
the width of the "inked" rectangle, which is what we had before.

Report x advance for cairo text width

---

piet/src/color.rs

Provide a method to construct colors based on the CIE HLC color space,
which is both colorimetrically sound and useful for communication; it
is the space advocated by freiefarbe.de.
Currently the implementation just creates an 8-bit per channel sRGB
value, but as we adopt high-gamut spaces we can make a better color
from the same inputs, so hopefully clients won't have to change.

Add Color::hlc constructor

---

piet-direct2d/src/lib.rs

I thought you explictly had to add a transform to a clip mask, but
it turns out it applies the current transform. So the old code was
actually doing the transform twice.

Don't apply transform to d2 clip mask

---

piet-cairo/src/lib.rs
piet-common/src/cairo_back.rs
piet-common/src/direct2d_back.rs
piet-common/src/lib.rs
piet-common/src/web_back.rs
piet-direct2d/src/lib.rs
piet-web/src/lib.rs

This patch exposes the backend-specific associated types for brushes,
text layout, and images.
It has similar goals as #37, but actually exposes all types as concrete
types, not just as type aliases for associated types. When these types
are hidden (as was the case for `Brush` in the d2d backend) then doing
an impl of a trait on the type causes coherence problems.
Also some updates to the documentation, making sure the new types (as
well as the `Piet` type alias) show up in documentation.

Expose associated types

---

piet-cairo/src/lib.rs
piet-common/examples/png.rs
piet-direct2d/src/conv.rs
piet-direct2d/src/lib.rs
piet-test/src/picture_0.rs
piet-test/src/picture_1.rs
piet-test/src/picture_3.rs
piet-test/src/picture_4.rs
piet-web/src/lib.rs
piet/src/color.rs
piet/src/gradient.rs
piet/src/lib.rs
piet/src/null_renderer.rs
piet/src/render_context.rs
piet/src/shapes.rs

Allow Color as brush argument to stroke and fill. Provide a new, more
ergonomic Gradient that uses UnitPoint, and let that be the argument to
stroke and fill as well.
Rolls in a few Color ergonomic improvements (#71).
Also adds a new `NullRenderContext` which is useful for doctests.
Fixes #72

More ergonomic brushes

---

piet/src/render_context.rs

Mentioned on zulip, but how do we feel about the name `IntoBrush`? I think it more clearly expresses the intention of this trait.
(my main thinking here is: when this shows up in a method signature, how do people interpret it?)

Tweak IBrush docs

---

piet/src/lib.rs
piet/src/null_renderer.rs

The blanket attribute on the module wasn't respected by the piet-common re-export.
Fixes #78

Move hidden to individual NullRenderContext types

---

piet/src/gradient.rs

There's no reason these can't be used as well, as opposed to explicitly
creating a gradient. There's a bit of extra cloning which we could
probably avoid, but unlikely to be a serious performance problem.

Add IBrush impl for FixedGradient

---

piet/src/gradient.rs

This fills the same role as LinearGradient; it is a gradient
description that can b reused for different shapes of different
sizes.

Add RadialGradient

---

piet-test/src/lib.rs
piet-test/src/picture_5.rs

Basic example that's text-only. In preparation for testing api changes
and new features.

Add text example to piet-test

---

.gitignore
piet-cairo/src/lib.rs
piet-direct2d/src/lib.rs
piet-test/src/picture_0.rs
piet-test/src/picture_5.rs
piet-web/src/lib.rs
piet/src/null_renderer.rs
piet/src/text.rs

Creating Font and TextLayout builders should not fail, so to avoid
unnecessary unwrapping for users, this commit removes the Result from
the `new_font_by_name` and `new_text_layout` methods in the `Text`
trait.
This is a user API breaking change.
Also updated implementers of `Text` (all existing backends):
- null_renderer
- direct2d
- cairo
- web
Also updated user of `Text`, `piet-crate`.
As an ergonomic change for devs, this commit also:
- adds `#![cfg(windows)]` to the `direct-2d` backend so that it does
not attempt to compile on linux.
- adds `.cargo` to .gitignore; it's used for cross compilation config
Closes #76

Remove `Result` when creating Font and TextLayout builders

---

piet-direct2d/src/lib.rs
piet-test/src/picture_0.rs

Do a slightly more inefficient conversion to bezier paths so we can
tell in advance whether a subpath needs to be closed. This is a bit of
a workaround, as there are plans to improve the direct2d bindings so
we can set the is_closed at the end of the subpath, enabling a single
pass of iteration (tracked in #65).

Fix closed paths on stroke (d2d)

---

piet/src/color.rs

These could probably be 'gray' since we spell colour color, but I'm easy.
Was also tempted to add,
```rust
#[inline]
#[doc(hidden)]
fn gray(value: f64) -> Color {
Color::grey(value)
}
```
but 🤷‍♂
closes #95

Add Color::grey and Color::grey8

---

piet-cairo/src/grapheme.rs
piet-cairo/src/lib.rs
piet-direct2d/src/lib.rs
piet-web/src/grapheme.rs
piet-web/src/lib.rs
piet/src/text.rs

`is_text` is not useful in piet's text api at the moment. It was a holdover from the initial port from directwrite.
If we need it later, we can add it back. For now it's just confusing.

[text] remove unused is_text

---

piet-cairo/src/lib.rs
piet-web/examples/basic/src/lib.rs
piet-web/src/lib.rs

Hit test point was hanging (infinte loop in binary search). This should fix.
The issue was mixing up grapheme index and text position when updating the binary search slice.
This should hopefully provide a complete fix for the issue.
refer: #104

[text] fix hanging in hit test point binary search

---

piet/src/shapes.rs

This seems like a bug to me. Changing it to a borrow makes the function more useful.

Fix StrokeStyle.set_miter_limit by borrowing instead of moving.

---

Cargo.toml
piet-svg/Cargo.toml
piet-svg/examples/basic-svg.rs
piet-svg/src/lib.rs

Lightly tested; produces output similar to the cairo backend for test images 1, 3 and 4. Attempts to use text and images will produce `NotSupported` error; the `unimplemented` invocations are all statically unreachable as a result.
For some reason I couldn't get SVG line elements to display, but paths work fine and are more concise anyway.

Partial SVG backend

---

piet-cairo/src/lib.rs
piet-direct2d/src/lib.rs
piet-svg/src/lib.rs
piet-web/src/lib.rs
piet/src/null_renderer.rs
piet/src/render_context.rs

This is related to https://github.com/xi-editor/druid/issues/430 and exposes `current_transform()` and required for https://github.com/xi-editor/druid/pull/466

Expose current_transform() for contexts

---

piet-svg/Cargo.toml

`cargo publish` complains if description is missing.

Add missing fields to piet-svg/Cargo.toml

---

.azure-pipelines.yml

Azure Pipelines will shortly stop supporting macOS 10.13.

Increment macOS version

---

piet-test/src/picture_1.rs

see https://github.com/rust-lang/rust/issues/66145

Use `.iter()` instead of `.into_iter()` on array

---

piet-common/src/direct2d_back.rs

Do cleanup in `BitmapTarget::into_raw_pixels` on error.

[d2d] Fix crash on unsupported image format

---

piet-cairo/src/lib.rs
piet-common/src/cairo_back.rs

This makes cairo behave like d2d, which keeps me honest when writing code against the piet api.
I'm not sure this makes sense to include, But I'm also not sure it doesn't. 🤔

Add phantom lifetime to cairo Text object to match d2d API

---

piet-svg/src/lib.rs
piet-svg/src/text.rs
piet-test/src/picture_0.rs
piet-test/src/picture_1.rs
piet-test/src/picture_2.rs
piet/src/render_context.rs

Includes a change from `&self` to `self` for `render_context::ImageFormat::bytes_per_pixel`, referenced at https://github.com/linebender/piet/pull/133#discussion_r377208811
This should have no effect on API

Clippy cleanup

---

LICENSE-APACHE

Copy and paste error: name and date in LICENSE-APACHE is Maik Klein and 2016. Changed these respectively to Raph Levien and 2019, in order to match LICENSE-MIT.

Correct date and name in LICENSE-APACHE

---

piet-direct2d/src/dwrite.rs
piet-direct2d/src/text.rs

[d2d] Derive `Clone` for `DwriteFactory`

---

piet-common/src/direct2d_back.rs
piet-common/src/lib.rs

The common types `Brush` and `Image` got removed from the Direct2D backend with #111. They weren't removed from other backends nor did the removal have a deprecation period. Thus I imagine it was a mistake.
This PR adds the types back. It also adds a test to prevent accidental removal in the future.

Restore common types for Direct2D.

---

piet-direct2d/src/conv.rs

The new rust release introduced [a clippy error](https://rust-lang.github.io/rust-clippy/master/index.html#option_as_ref_deref) in [the CI](https://github.com/linebender/piet/runs/503565146). This PR fixes that error as recommended by the documentation.

Fix clippy error introduced with Rust 1.42.

---

piet-cairo/src/lib.rs
piet-direct2d/src/lib.rs
piet-svg/src/lib.rs
piet-test/src/picture_0.rs
piet-web/src/lib.rs
piet/src/null_renderer.rs
piet/src/render_context.rs

This PR expands the `draw_image` API call by adding a `src_rect` parameter. The drawing works as before, but now it uses the area of the image that is specified.
This is motivated by an image gallery app I'm writing using druid, where I need to show different areas of known images for every animation frame.
Previously this was possible by either having different images in memory or using `clip`. The new API makes it easier and probably more efficient.
Keeping ergonomics in mind for people who just want to draw the whole image (or upgrade to this new API) I also wanted it to be easy to do that. I tried a few ways of doing this.
First idea was to use `Option<impl Into<Rect>>` but unfortunately this ended up looking less than ideal.
```rust
Some(Rect::new(10.0, 10.0, 20.0, 20.0)) // Subimage …
```

Add draw_image_area to RenderContext.

---

.github/workflows/ci.yml

Checkout v1 is broken, see [druid#724](https://github.com/xi-editor/druid/pull/724) for more.

Update github actions checkout to v2.

---

piet-web/src/lib.rs

WebFont, WebFontBuilder and WebTextLayoutBuilder were not exported in
piet-web but expected in piet-common.
The compilation error on `cargo build --target wasm32-unknown-unknown` was:
```rust
error[E0412]: cannot find type `WebFont` in this scope
--> piet-common/src/web_back.rs:20:21
|
20 | pub type PietFont = WebFont;
|                     ^^^^^^^ not found in this scope
error[E0412]: cannot find type `WebFontBuilder` in this scope
--> piet-common/src/web_back.rs:25:32
|
25 | pub type PietFontBuilder<'a> = WebFontBuilder;
| -------------------------------^^^^^^^^^^^^^^-
| |                              |
| |                              help: a type alias with a similar name exists: `PietFontBuilder`
| similarly named type alias `PietFontBuilder` defined here
error[E0412]: cannot find …
```

Fix piet-web build

---

.github/workflows/ci.yml

This PR will add `wasm32-unknown-unknown` clippy & build to the CI so that issues like #151 won't get past us again.

Add proper wasm32 CI testing.

---

.github/workflows/ci.yml
piet-common/examples/png.rs

Cargo can't natively run wasm32 tests, but we can at least build them to catch compile errors.
The `png` example doesn't work with wasm32 right now due to lacking `piet_common::Device`. I disabled the example for wasm32 until it gets fixed.
In the future we might be able to get proper testing via `wasm-pack test` and node.js or something, but I'm not sure how all of that works so it's not part of this PR.

Add wasm32 test compiling of piet-web/piet-common to the CI.

---

piet-common/Cargo.toml
piet-common/src/lib.rs

Previously it was possible to select both cairo and the web
backend by passing --features=web without having the target be
wasm32.
This attempts to simplfy how we choose the backend.
We will use cairo if it is selected explicitly, or if we're not on
wasm32, windows, or don't see the 'web' feature;
We will use d2d if we're on windows and don't see the 'cairo' feature;
And we will use the web backend if our target arch is wasm32 or
we see the "web" feature.
We will fail to compile if we cannot select a backend.

Fix backend choice collision

---

piet-web/examples/basic/Cargo.toml
piet-web/examples/basic/src/lib.rs

This commit tweaks the tests to pass, and adds a useful console error hook to capture panics in the browser console.
Admittedly, the tweak in tests is perhaps dependent on my system configuration, so it will be worth for reviewers to verify whether the tests pass. To do so please check the console log in the browser.

Fix piet-web tests & add console hook for panics

---

piet-web/src/lib.rs

This enables proper browser zooming through the dpi/devicePixelRatio mechanism.
For reference this addresses the zooming issue in druid wasm support found in the [#759](https://github.com/xi-editor/druid/pull/759).

Switch to offset_{width,height} when clearing web context

---

piet-web/examples/basic/src/lib.rs
piet-web/src/lib.rs

Specifically, the lifetime of `WebRenderContext` is changed to not depend on lifetimes of  `CanvasRenderingContext2d` and `Window` objects, since these lifetimes don't actually enforce the existence of web resources anyways.
The `mut `is also removed from `CanvasRenderingContext2d` since its API has no `mut` calls and this generally makes the `WebRenderContext` difficult to use in libraries like druid.
For compatibility the `WebRenderContext` maintains a phantom lifetime placeholder for compatibility as well as for anticipating a correct lifetime there.

Remove refs from WebRenderContext constructor API

---

piet/src/color.rs

I find myself copy pasting a "split_rgba" function in a few projects. By impling From we get Into for free and this will cover my use case. I could also add a From<[f64; 4]> / From<[u8; 4]> if those are interesting, but I haven't personally needed those yet.

Impl From for Color

---

piet-cairo/src/text.rs
piet-direct2d/src/text.rs
piet-svg/src/text.rs
piet-test/src/picture_0.rs
piet-test/src/picture_5.rs
piet-web/src/text.rs
piet/src/null_renderer.rs
piet/src/text.rs

Updates `Text::new_text_layout` and `TextLayout::update_width` to use
`impl Into<Option<f64>>` for width and new width parameters. Internally,
`f64` is still used.
Fixed a bug for piet-web and piet-d2d where `TextLayout::update_width` did
not recalculate new width. Should add tests for recalculating width.

[text] TextLayout width as Option<f64> instead of f64, fix update_width

---

piet-cairo/src/lib.rs
piet-cairo/src/text.rs
piet-test/src/picture_5.rs
piet-web/src/lib.rs
piet-web/src/text.rs

Whoops, `draw_text` was not implemented for web and cairo backends. This fixes that.
Should fix #169

[cairo, web] impl draw_text for multiline

---

piet-web/Cargo.toml
piet-web/src/lib.rs

Follow-up to https://github.com/linebender/piet/pull/117
The newest version of `wasm-bindgen` now exposes `get_transform()`

current_transform() for web backend

---

piet-common/Cargo.toml
piet-common/src/web_back.rs

This PR adds a placeholder for the bitmap target rendering mechanism present in other backends. In the current state this PR will enable druid unit tests to be built with WASM, although their execution will need to be thought out further.
I intend this PR to simply get the ball rolling toward getting testing working for the wasm backend in druid since https://github.com/xi-editor/druid/pull/759 doesn't provide any testing in wasm.

Wasm bitmap target

---

piet/src/color.rs

- make Color::as_rgba take &self (fixes #180)
- rename Color::as_rgba_u8 to Color::as_rgba8 (matches constructor)

Tweak color as_ methods

---

piet-cairo/src/lib.rs
piet-common/src/cairo_back.rs
piet-common/src/direct2d_back.rs
piet-common/src/web_back.rs
piet-direct2d/src/d2d.rs
piet-direct2d/src/dwrite.rs
piet-direct2d/src/lib.rs
piet-svg/src/lib.rs
piet-svg/src/text.rs
piet/src/error.rs

This removes ErrorKind and the new_error method; the Error type
can just be used directly when needed.
I was in this code to add a MissingFont error, and did a bit of cleanup.

Simplify piet Errors

---

piet/src/samples/picture_0.rs

This does some cleanup, and a few tweaks:
- we now draw the area that is used for clipping
- the image is simpler, to make it easier to distinguish whether
it is oriented correctly
before:
after:

Fixup sample_picture_0

---

.github/workflows/ci.yml
Cargo.toml
piet-common/Cargo.toml
piet-common/src/cg_back.rs
piet-common/src/lib.rs
piet-coregraphics/Cargo.toml
piet-coregraphics/examples/basic-cg.rs
piet-coregraphics/examples/test-picture.rs
piet-coregraphics/src/blurred_rect.rs
piet-coregraphics/src/ct_helpers.rs
piet-coregraphics/src/gradient.rs
piet-coregraphics/src/lib.rs
piet-coregraphics/src/text.rs
piet/src/samples/picture_5.rs

This is still work in progress. It's based off #4, updated for API changes and so on. In its current state, paths work and there is code for images, but nothing on gradients or text yet.

Core Graphics back-end

---

piet-coregraphics/src/lib.rs

Images were not drawing correctly if the rect they were drawn into
was not at the origin.
This is related to coregraphics coordinate space wonkiness; the
easiest solution I see is to transform the context and then draw
the image at the origin, instead of bothering with correctly
transforming the rect.
This wasn't an issue in druid, which always draws images at the origin of the image widget; it was a problem when using piet directly, though.

[cg] Fix image drawing

---

piet-cairo/src/lib.rs
piet-coregraphics/src/lib.rs

As discovered in [druid#922](https://github.com/xi-editor/druid/issues/922) the cairo context given by GTK has a transform already applied to it. This PR mimics the coregraphics solution to do the bookkeeping ourselves.

Fix current_transform with GTK cairo.

---

.github/workflows/ci.yml
README.md
piet-cairo/Cargo.toml
piet-common/Cargo.toml
piet-common/src/cairo_back.rs
piet-common/src/cg_back.rs
piet-common/src/direct2d_back.rs
piet-common/src/web_back.rs
piet-coregraphics/Cargo.toml
piet-direct2d/Cargo.toml
piet-svg/Cargo.toml
piet-web/Cargo.toml

This PR refactors the CI script to allow for easier expansion and testing of features. The cargo manifest files are cleaned up a bit and unified in style. I also updated `README.md` to better reflect the current state of things.
Fixes  #192.

Clean up workspace compilation and testing.

---

.github/workflows/ci.yml

The doc tests are marked as required, so they should be done with the stable compiler instead.

Do doc tests with the stable compiler.

---

piet-cairo/src/text.rs
piet-common/src/web_back.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/text.rs
piet-svg/src/text.rs
piet-web/src/lib.rs
piet-web/src/text.rs
piet/src/null_renderer.rs
piet/src/text.rs

All implementations of `Text` should now be clonable thus clearing up the lifetime issues around threading as discussed on Zulip.
Required breaking `piet-web`'s `Text` implementation into it's own struct adjacent to its `RenderContext` struct. That is a breaking change which will require modification to druid's web shell. Once this seems to be passing CI (which I bet it will not initially pass) I will submit a hopefully minor druid PR to make the required changes.

Make `Text` trait require `Clone` and implement for all backends

---

piet-cairo/src/lib.rs

Should the cairo surface be flushed on `finish`? It should definitely be flushed somewhere...

Flush the surface on `finish`.

---

piet-common/Cargo.toml
piet-common/src/cairo_back.rs
piet-common/src/cg_back.rs
piet-common/src/direct2d_back.rs
piet-common/src/web_back.rs

This adds the functions that I suggested in #212. There are two sad things about this PR that I couldn't figure out how to improve:
- on web, I couldn't find a way to access the borrowed pixels, so `copy_raw_pixels` has to copy them twice :|
- cairo-rs has some safety checks that made it a pain to get the data out without destroying the context first. I ended up needing to use unsafe.

Add a BitmapTarget::copy_raw_pixels function

---

clippy.toml
piet-cairo/src/lib.rs
piet-cairo/src/text.rs
piet-common/src/lib.rs
piet-coregraphics/src/lib.rs
piet-direct2d/src/d2d.rs
piet-direct2d/src/lib.rs
piet-svg/src/lib.rs
piet-web/src/lib.rs
piet-web/src/text.rs
piet/src/gradient.rs
piet/src/lib.rs
rustfmt.toml

Rust 1.44 moved the `trivially_copy_pass_by_ref` clippy lint to pedantic. As discussed on [zulip](https://xi.zulipchat.com/#narrow/stream/147926-druid/topic/Scale.20clippy.20fail) let's turn it back on, at least for now.

Enable trivially_copy_pass_by_ref clippy lint.

---

piet-common/Cargo.toml
piet-common/src/cairo_back.rs
piet-common/src/cg_back.rs
piet-common/src/lib.rs
piet-common/src/web_back.rs
piet-direct2d/src/d2d.rs
piet-direct2d/src/d3d.rs
piet-direct2d/src/dwrite.rs

Fixes #211, and also makes Device !Sync, jut to reduce portability friction.
Note that there are currently no checks for this. If you're willing to add `static-assertions` as a dev-dep, I could add tests...

Make Device Send and !Sync on all backends.

---

piet-cairo/src/text.rs
piet-coregraphics/src/ct_helpers.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/dwrite.rs
piet-direct2d/src/text.rs
piet-svg/src/text.rs
piet-web/src/text.rs
piet/src/null_renderer.rs
piet/src/text.rs

This is intended as a very simple, non-falible way of getting
a font suitable for UI.
I'd initially imagined a slightly more complex API, that included support for a few different fonts and styles, but I backed away and just went with the simplest thing I could picture.
This has only been tested on macOS. cairo should work, but windows is a bit hacky.
Question: should this at least support italics?

Add system_font method to Text trait

---

piet-cairo/examples/test-picture.rs
piet-direct2d/examples/test-picture.rs

The example binary that draws sample pictures are now
all called `test-picture`, and they now all output files
in the format, "$BACKEND-test-$SAMPLE_NUMBER".

Standardize sample painting examples and output

---

piet-cairo/src/text.rs
piet-coregraphics/Cargo.toml
piet-coregraphics/src/ct_helpers.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/dwrite.rs
piet-direct2d/src/text.rs
piet-svg/src/text.rs
piet-web/src/text.rs
piet/src/null_renderer.rs
piet/src/samples/mod.rs
piet/src/samples/picture_7.rs
piet/src/text.rs

This adds a `TextAlignment` enum, which can be used with `TextLayoutBuilder`.
It also uses this on mac and windows (windows impl was written blind, will fix it up shortly).
This is based off of #225, because it includes a test drawing that exercises these layouts, and which on macOS looks like,
Also looking at that sample is making me think that we're not doing hidpi correctly when writing out the PNGs or something? I'll have to look into that.

Text alignment

---

piet-cairo/examples/test-picture.rs
piet-cairo/src/lib.rs
piet-common/src/cairo_back.rs

The reference kept by `CairoRenderContext` should be shared. The Cairo context is internally reference-counted and, as far as I can tell, thread-safe.
The fact that it now keeps an exclusive reference is an inconvenience in combination with GTK. The callback of the [`draw` signal](https://docs.rs/gtk/0.8.1/gtk/trait.WidgetExt.html#tymethod.connect_draw) is only provided a shared reference to a context which means that you have to clone it first.

For convenience, use a shared reference to the Cairo context

---

piet-coregraphics/src/text.rs

This didn't matter when we didn't really support multi-line layout,
but this calculation was wrong at the start of lines.

[cg] Add line_number_for_utf8_offset (and fix logic error)

---

piet-cairo/src/text.rs
piet-coregraphics/src/ct_helpers.rs
piet-coregraphics/src/text.rs
piet-direct2d/Cargo.toml
piet-direct2d/src/d2d.rs
piet-direct2d/src/dwrite.rs
piet-direct2d/src/lib.rs
piet-direct2d/src/text.rs
piet-direct2d/src/text/lines.rs
piet-svg/src/text.rs
piet-web/src/text.rs
piet/src/null_renderer.rs
piet/src/samples/mod.rs
piet/src/samples/picture_7.rs
piet/src/samples/picture_8.rs
piet/src/text.rs
piet/src/util.rs

This adds support for rich text, with implementations for mac and windows.
A few things are in a funny state as a result of this work:
***font construction***: currently to construct a font you pass a name and a size, and get back a `FontBuilder`; the idea at the time was likely that you would set properties like weight/style on this builder, and then build your font object. We're moving closer to a world like CSS, where you don't generally use font objects directly, but instead specify familes/sizes/weights individually on the layout. This has some API implications:
- `FontBuilder` can go, and methods that construct fonts can return `Option<Font>`.
- The `Text::font` method is semantically less about *creating* a font than it is about validating the existence of a font family.
- …

Initial rich text support

---

piet-cairo/src/text.rs
piet-direct2d/src/text.rs

This is cleanup; the rationale is that using a macro means we can
actually see what line causes a test failure, and I have some test
failures coming up. :grin:

Replace assert_close_to with a macro, remove unnecessary casts

---

piet-cairo/src/lib.rs
piet-cairo/src/text.rs
piet-cairo/src/text/lines.rs
piet-coregraphics/src/text.rs
piet/src/text.rs

I had initially wanted to replace `start_offset` and `end_offset` with a single `range: Range<usize>` member, but this didn't end up feeling much more ergonomic, and was a fairly invasive change.
This also touches up the docs for `start_offset` and `end_offset`.

Add TextLayout::range convenience method

---

piet-cairo/src/text.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/text.rs
piet-svg/src/text.rs
piet-web/src/text.rs
piet-web/src/text/lines.rs
piet/src/null_renderer.rs
piet/src/samples/picture_0.rs
piet/src/samples/picture_5.rs
piet/src/text.rs

This replaces TextLayout::width; it is reasonable that the caller
would want to know the size of the entire layout, for things like
drawing a background or similar.

Add TextLayout::size method

---

piet-cairo/src/lib.rs
piet-cairo/src/text.rs
piet-cairo/src/text/lines.rs
piet-coregraphics/src/lib.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/lib.rs
piet-direct2d/src/text/lines.rs
piet-web/src/lib.rs
piet-web/src/text.rs
piet-web/src/text/lines.rs
piet/src/samples/mod.rs
piet/src/samples/picture_8.rs
piet/src/samples/picture_9.rs
piet/src/text.rs

This changes behaviour and will likely break text in druid, but that's future work.
in addition, LineMetric::cumulative_height is replaced with LineMetric::y_offset, which (I think) better communicates the intent of this value, which is to determine the position of the line relative to the origin of the layout.
(draft so I can run CI)

Use top-left as text origin

---

piet-cairo/src/text.rs
piet-coregraphics/src/ct_helpers.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/dwrite.rs
piet-direct2d/src/text.rs
piet-svg/src/text.rs
piet-web/src/text.rs
piet/src/null_renderer.rs
piet/src/samples/mod.rs
piet/src/samples/picture_10.rs
piet/src/samples/picture_9.rs
piet/src/text.rs

This method returns the bounding rectangle of the glyphs in the
layout, relative to the layout's origin.
It also adds a new sample picture (`picture_10.rs`) that shows the
difference between this region and the layout's bounds in an
exaggerated case (zalgo).

Add TextLayout::image_bounds

---

piet-direct2d/src/text.rs
piet-direct2d/src/text/lines.rs
piet/src/util.rs

This was previously using utf-16, which was presumably an oversight.

[d2d] Use utf-8 for ranges in LineMetric

---

piet-cairo/src/text.rs
piet-cairo/src/text/grapheme.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/text.rs
piet-svg/src/text.rs
piet-web/src/text.rs
piet-web/src/text/grapheme.rs
piet/src/null_renderer.rs
piet/src/samples/mod.rs
piet/src/samples/picture_11.rs
piet/src/text.rs

This is intended to simplify this API a bit; the existing design
was based on DirectWrite's API, but we aren't going to implement
that API directly so I think this is a reasonable simplification.
- HitTestTextPosition is renamed HitTestPosition
- HitTestPosition loses the `metrics` field
- HitTestPoint has an `idx` field, instead of a `HitTestMetrics`
member
This also includes a new sample picture or visualizing the results of hit-testing, which looks something like:
this has revealed an inconsistency in dw, where we're returning the top of the line instead of the baseline in `HitTestPosition`; will open an issue for that shortly.
I'm also considering returning a line number along with the `Point` for `hit_test_text_position`, to make it easier to get the line metrics for the relevant …

Remove HitTestMetrics, simplify other hit testing types

---

piet-svg/src/lib.rs

The `<color>` value for the `fill` and `stroke` attributes for example, typically, refers to a solid color (sRGB).
Applications like Inkscape or Affinity don't support the additional alpha channel which is currently added.
This PR splits the color value into the RGB and A channels and sets the corresponding attributes.
Example output:
```
<svg xmlns="http://www.w3.org/2000/svg">
<path d="M20 250C48.00262530267052 250 62.00393795400579 250 72.69952498697732 244.5503262094184C77.37444060334367 242.1683377286408 81.6453050202178 239.06537309843694 85.35533905932736 235.35533905932738C89.06537309843692 231.64530502021782 92.16833772864078 227.3744406033437 94.55032620941837 222.69952498697734C100 212.00393795400578 100 198.00262530267054 100 170" fill="none" stroke="#cc331a" …
```

svg: split opacity and color for increased compatibility

---

piet-coregraphics/src/text.rs
piet-direct2d/src/dwrite.rs
piet-direct2d/src/text.rs
piet/src/samples/picture_8.rs
piet/src/text.rs

This will be necessary when attributes for specific ranges can
override default attributes.

Make italic/underline text attributes take a boolean

---

piet-cairo/examples/test-picture.rs
piet-coregraphics/Cargo.toml
piet-coregraphics/examples/test-picture.rs
piet-direct2d/examples/test-picture.rs
piet-direct2d/src/d3d.rs
piet-svg/examples/basic-svg.rs
piet-web/examples/basic/src/lib.rs
piet/Cargo.toml
piet/src/error.rs
piet/src/lib.rs
piet/src/samples/mod.rs

This sets up doing snapshot testing over sample images. The actual
testing code isn't written yet, but this makes it easy to run all
of the samples, and to write them to a specific target directory.

Refactor sample image code

---

piet-cairo/src/text.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/text.rs
piet-direct2d/src/text/lines.rs
piet-svg/src/text.rs
piet-web/src/text.rs
piet/src/null_renderer.rs
piet/src/samples/picture_0.rs
piet/src/samples/picture_10.rs
piet/src/samples/picture_11.rs
piet/src/samples/picture_5.rs
piet/src/samples/picture_7.rs
piet/src/samples/picture_8.rs
piet/src/samples/picture_9.rs
piet/src/text.rs

This now shifts almost everything to the builder.
It also adds a new TextLayoutBuilder::font(Font, f64) method for
easily setting the layout's default family and size.
This looks a bit funny right now because we haven't removed size from the font object yet; that will be the next patch.

Update new_text_layout API

---

piet-cairo/src/lib.rs
piet-cairo/src/text.rs
piet-cairo/src/text/grapheme.rs
piet-cairo/src/text/lines.rs
piet-common/src/cairo_back.rs
piet-common/src/cg_back.rs
piet-common/src/direct2d_back.rs
piet-common/src/lib.rs
piet-common/src/web_back.rs
piet-coregraphics/src/ct_helpers.rs
piet-coregraphics/src/lib.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/dwrite.rs
piet-direct2d/src/lib.rs
piet-direct2d/src/text.rs
piet-direct2d/src/text/lines.rs
piet-svg/src/text.rs
piet-web/src/lib.rs
piet-web/src/text.rs
piet/src/null_renderer.rs
piet/src/samples/picture_0.rs
piet/src/samples/picture_5.rs
piet/src/samples/picture_8.rs
piet/src/samples/picture_9.rs
piet/src/text.rs
piet/src/util.rs

This PR is now a big rollup of font-related changes, including:
- use of a `FontFamily` type as the token you receive when querying a font
- non-failable 'generic font families' (`FontFamily::SERIF`, e.g.)
- removal of `Font` and `FontBuilder` traits
- a bunch of doc improvements around text
This is hopefully the last major API change; there are still a few API additions to make, but hopefully nothing earth-shattering.

Font API changes

---

piet-cairo/src/text/lines.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/text/lines.rs
piet-web/src/text/lines.rs
piet/src/text.rs

This was marked deprecated but we've already broken the API so
no need to keep it around.

Remove LineMetric.cumulative_height

---

piet-cairo/src/text.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/text.rs
piet-svg/src/text.rs
piet-web/src/text.rs
piet/src/null_renderer.rs
piet/src/samples/mod.rs
piet/src/samples/picture_12.rs
piet/src/text.rs

The TextLayout::text was added because we need access to the
length of the text in order to provide a nice default implementation
for TextLayout::rects_for_range.
This also includes a new sample picture, picture_12, which
illustrates drawing selections and highlights.

Add TextLayout::text and TextLayout::rects_for_range

---

.github/workflows/ci.yml
piet-cairo/src/text.rs
piet-coregraphics/Cargo.toml
piet-coregraphics/src/ct_helpers.rs
piet-coregraphics/src/text.rs
piet-direct2d/Cargo.toml
piet-direct2d/src/dwrite.rs
piet-direct2d/src/text.rs
piet-svg/src/text.rs
piet-web/src/text.rs
piet/src/error.rs
piet/src/null_renderer.rs
piet/src/samples/mod.rs
piet/src/samples/picture_13.rs
piet/src/text.rs

This implements the minimum possible version of custom fonts.
- fonts can be loaded, but not unloaded
- loaded fonts are referred to by their family name

Font loading

---

piet-coregraphics/src/ct_helpers.rs
piet-coregraphics/src/text.rs
piet/src/samples/mod.rs
piet/src/samples/picture_14.rs
piet/src/text.rs

We don't expose fine grained control for variable fonts, but if
a font has a weight axis, we will use it.

Support wght axis when present on a variable font

---

piet/src/samples/mod.rs

As previously written, the --compare flag would only work in the
company of --all.

Allow comparison of individual snapshots

---

piet-cairo/src/text.rs
piet-cairo/src/text/grapheme.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/text.rs
piet-web/src/text.rs
piet-web/src/text/grapheme.rs
piet/src/text.rs

We will now always clamp an out of bounds position to the end of
the text, and we will always panic if the text position is not
a character boundary.

Standardize behaviour of TextLayout::hit_test_text_position

---

piet-cairo/src/text.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/text.rs
piet-svg/src/text.rs
piet-web/src/text.rs
piet/src/null_renderer.rs
piet/src/samples/picture_11.rs
piet/src/text.rs

The None path was only being used in directwrite, and only when
encountering an error from winapi. In that case we will now
just return the first text position (panicking would also be a
reasonable choice).
This is based off of #262; they're both addressing inconsistencies in the behaviour of the hit_test_text_position method.

Make TextLayout::hit_test_text_position return non Option

---

piet-common/src/cg_back.rs
piet-coregraphics/examples/test-picture.rs
piet-coregraphics/src/lib.rs
piet-coregraphics/src/text.rs

The CoreGraphicsText struct now has state, and it should not be
created anew each time a RenderContext is created.
This is something I ran into immediately when trying to update druid; we expect to just be able to create text objects out of thin air.

[cg] Reuse text object when creating context

---

piet-cairo/src/text.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/text.rs
piet/src/text.rs

This attempts to address the issue of how to determine the correct
cursor size in an empty layout.
Essentially: when constructing the layout, we compute the line height
and baseline values that would be used for the layout's default
font and font size, and we stash these; if the layout is empty, we
use these values to synthesize the result of calls to hit_test_position
and line_metric.
- closes #268

Compute default line height for empty layout

---

piet/src/text.rs

When updating druid, it was often annoyingly verbose to set the
text color.

Add text_color convenience method to layout builder

---

piet-direct2d/src/dwrite.rs
piet-direct2d/src/lib.rs
piet-direct2d/src/text.rs
piet-direct2d/src/text/lines.rs

This saves us from having to have a handle to the DeviceContext
in the Text object, which was a major headache when we tried to
integrate this work into druid.

[d2d] Generate brushes lazily in TextLayout

---

piet-common/src/lib.rs
piet-common/src/web_back.rs
piet-web/src/lib.rs

I do not know why this worked before, why it stopped working, or
why it matters; but this mismatch was blocking the compilation
of the druid web backend.

[web] Fix signatures to match other piet-common backends

---

piet-coregraphics/src/text.rs
piet-direct2d/src/text.rs

We expect default attributes to always be added before any range
attributes, and that range attributes are added in non-descending order;
this will now crash more aggressively when those conditions are broken.

Add asserts to check TextLayoutBuilder used as expected

---

piet-cairo/src/text.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/dwrite.rs
piet-direct2d/src/text.rs
piet/src/font.rs
piet/src/samples/picture_13.rs
piet/src/samples/picture_5.rs
piet/src/samples/picture_8.rs
piet/src/text.rs
piet/src/util.rs

based off of #284.
This was motivated by wondering how I would go about storing something like font style in the druid environment, or stash it in other places, and convincing myself that this does make more sense as an independent type.

Add FontStyle enum

---

piet-cairo/src/text.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/text.rs

- closes #292
This also fixes a bug in the d2d backend where we were not correctly recomputing various metrics when the width of the layout changed.

TextLayout::size should use line height with empty string

---

piet-cairo/src/text.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/text.rs
piet-svg/src/text.rs
piet-web/src/text.rs
piet/src/null_renderer.rs
piet/src/text.rs

This will still allow the simple case of passing a string slice, but
will also let druid share string objects with piet, which should enable
better APIs that aren't giving up efficiency.
Another benefit of this work is making cloning of layout objects
cheaper.
closes #295

Make new_text_layout take impl Into<Arc<str>>

---

piet-coregraphics/src/ct_helpers.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/dwrite.rs
piet-direct2d/src/text.rs
piet/src/samples/picture_5.rs
piet/src/samples/picture_8.rs
piet/src/text.rs
piet/src/util.rs

Made by basically just copying underline. Just like underline this does not have any support for formatting the strikethrough itself, although the underlying apis support it. ~~I do not have access to a mac to test the coregraphics implementation (nor have I ever written mac code before)~~, however the d2d implementation appears to work on my Win 10 box. This will need a snapshots update.

Add support for strikethrough formatting on text.

---

piet-coregraphics/src/text.rs
piet-direct2d/src/text.rs
piet-direct2d/src/text/lines.rs

This makes these types cheaper to clone.
Closes #296
Might as well get this in before releasing 0.2.0-pre3 🤷

Use Rc<[T]> instead of Vec<T> in layout types

---

piet-direct2d/Cargo.toml
piet-direct2d/src/d2d.rs
piet-direct2d/src/lib.rs
piet-direct2d/src/text.rs
piet/src/color.rs

Fixes #303, fixes #304.
Doing this required a few weird changes: removing Clone on DeviceContext and adding it to Error, but it all works out. Apparently nothing was using the Clone on DeviceContext? Testing with https://github.com/smmalis37/sudoku_rust shows a massive responsiveness improvement.
Design questions:
Currently this is caching the full result of the CreateSolidBrush call. This means if the call fails we won't retry it until that brush leaves the cache. Only caching successful brushes would require doing something to work around wrap, so I went with this approach instead. Good enough or should I try to only cache successes?
Cache capacity. It supports powers of 2 up to 8192, I picked 64 arbitrarily.
Replacement strategy. Round robin is the simplest so I went with it. Lru is …

Cache solid color brushes in d2d.

---

piet-cairo/src/text.rs

This was mentioned by @smmalis37 before, and I encountered it just now while updating my project.
Warnings like this are quite annoying as they just keep spaming the terminal, I think this would be better off in a GitHub issue.

Remove warning about missing TextAlignment support with Cairo.

---

piet-direct2d/src/conv.rs
piet-direct2d/src/d2d.rs
piet-direct2d/src/lib.rs

Fixes #60.
I plan to tackle the rest of the TODO comments on this, but I wanted to ensure I'm doing things correctly first. I haven't done much testing, are the snapshots good enough or should I do more? Also, do the FillRules affect simple shapes? A quick read of the docs on msdn leads me to think no, but this is all new to me. If not then I'll probably refactor the two methods into just calling a combined `fill_impl`, but if there needs to be something more involved then they may stay separate.  And does calling fill on a line actually need to do any work (like I've currently got) or will it all be handled by `stroke` (which will then get specialized to call DrawLine)?

Add shape specializations to d2d.

---

piet-common/src/cg_back.rs

This apparently isn't actually used anywhere?

Fix incorrect type alias in piet-common

---

piet-cairo/src/text.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/text.rs
piet-direct2d/src/text/lines.rs
piet-svg/src/text.rs
piet-web/src/lib.rs
piet-web/src/text.rs
piet/src/null_renderer.rs
piet/src/text.rs

This is a further refinement of how we want to store the
actual text backing a layout object. The motivation here
is to allow the client maximum flexibility in terms of
how they store their text.
This moves from using `Arc<str>` everywhere to using
`Rc<dyn TextStorage>`; this introduces another layer
of pointer indirection in various cases, but saves us
needing to add a type parameter.

Add TextStorage trait

---

piet-coregraphics/src/text.rs

This was a mess in a number of ways, and would crash if called
when the layout had no lines.
The expected behaviour here is debatable; we could return the
empty string or we could return None. I chose to return the
empty string to match the behaviour of Layout::line_metric,
which still returns a metric when there are no lines (in that
case, so that we can draw the cursor in an empty layout).

Fix panic in line_range with empty string

---

.github/workflows/ci.yml
piet-cairo/src/text.rs
piet-common/tests/text.rs
piet-coregraphics/src/text.rs
piet/src/text.rs

This includes some of the conformance testing stuff from #326, which I will close. It is an attempt to unify the behaviour of a layout object when the layout text is the empty string.
This changes piet-coregraphics and piet-cairo to behave
like piet-d2d in this regard:
- An empty layout is considered to have a single line
- the text for this line (empty string) can be retrieved
- the LineMetric for this line can be retrieved; it will
be synthesized as needed (this was already in place)
This also adds conformance tests to piet-common that
check the consistency of this across implementations.

Standardize behaviour of empty TextLayout

---

piet-common/tests/text.rs
piet-coregraphics/src/text.rs
piet/src/text.rs

Previously it would return a rect with zero size.
This also removes a duplicate implementation of this
method in piet-coregraphics.
This is based off of #328

Make rects_for_range return nothing for empty range

---

piet-cairo/src/text.rs
piet-common/tests/text.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/text.rs
piet/src/text.rs

- this should be included in the layout's reported size
- this should be reported as an additional line (count_lines())
- this should be a valid cursor position during hit testing

Standardize handling of newline at EOF

---

piet-cairo/src/text.rs
piet-common/tests/text.rs
piet-coregraphics/src/text.rs
piet/src/util.rs

When there's a newline at the end of a visual line, a hit-test
at the end of that line should return the offset of the
character preceding the newline, not the newline itself.

Standardize hit_test_point on newline at EOL

---

piet/src/text.rs

I have some aspirations to use Arc<String> as a simple
editable text type in druid, and orphan rules oblige me
to have this impl'd for that to work.

Impl TextStorage for Arc<String> & Rc<String>

---

piet-common/Cargo.toml
piet-common/src/lib.rs

Previously you could optionally use cairo on macOS, but that
does not seem useful anymore.

Simplify selection of backend in piet-common

---

piet-common/tests/text.rs
piet-direct2d/src/text.rs

This is a less principled approach to fixing #339 than is
outlined in that issue, but is less invasive and works just as well.
This also fixes a test in piet-common that was intended to catch
this, but that was using a layout with a default font size, which
doesn't manifest this problem.
- fixes #339
- fixes https://github.com/linebender/druid/issues/1309

[d2d] Use default line height as height when text is empty

---

piet-web/examples/basic/src/lib.rs
piet-web/src/lib.rs
piet-web/src/text.rs

This doesn't support alignment, soft breaks, or style spans, but
it does support basic default styles and drawing of multiline,
when those lines are hard breaks.
- closes #311
before:
after:

Fix basic drawing of text on web

---

piet-coregraphics/Cargo.toml
piet-coregraphics/src/ct_helpers.rs
piet-direct2d/src/dwrite.rs
piet-direct2d/src/text.rs
piet/Cargo.toml
piet/src/util.rs

I had failed to notice that text alignment was not behaving as expected for RTL scripts on windows; it turns out that you *do* need to explicitly set the `DWRITE_READING_DIRECTION` in order for `DWRITE_TEXT_ALIGNMENT_LEADING` to correspond to the right edge in a RTL script.
In the examples below, the first two columns of arabic text should be aligned to the opposite edge than the corresponding columns of english text.

Correct rtl alignment

---

piet-coregraphics/src/text.rs
piet/src/samples/picture_11.rs

This fixes #349, by keeping a stash of x-offsets for lines on mac, and using these to determine the correct x-position for a given line.
This is based off of #352, which fixes a bug I noticed while investigating.

Account for alignment in hit testing

---

piet-cairo/src/text.rs
piet-common/tests/text.rs
piet-coregraphics/src/ct_helpers.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/text.rs
piet-svg/src/text.rs
piet-web/src/text.rs
piet/src/null_renderer.rs
piet/src/text.rs

Another little oversight. This will probably require us to go
to 0.3.0, but that will also let us get the greyscale image stuff
landed.
closes #357
I've only tested on mac, so i'm sure this will fail somewhere in CI. Also it looks like the cairo backend *was* including ws width, maybe? We'll find out shortly... 😬

Add TextLayout::trailing_whitespace_width

---

piet/src/samples/mod.rs

This came up on zulip, and should help somebody at some point.

Print a help message when running sample with invalid args

---

piet/src/color.rs

This patch adds the basic CSS3 colors as constants to `Color`. They are present as a convenience if you want to use a standard color. What do you think?

Add the basic colors from css3.

---

piet-cairo/examples/test-picture.rs
piet-coregraphics/examples/test-picture.rs
piet-direct2d/examples/test-picture.rs
piet-svg/examples/basic-svg.rs
piet-web/examples/basic/src/lib.rs
piet/src/samples/mod.rs

This patch is a response to a comment on the Zulip that showed it was hard to understand/use the `test_picture` examples.

Make help messages for `test_picture` more helpful.

---

piet-cairo/src/lib.rs
piet-common/tests/image.rs
piet-coregraphics/src/lib.rs
piet-direct2d/src/lib.rs

Whilst making an image viewer, I wanted a default value for the image to display. What I found is that if I used the default constructor `ImageBuf::empty` I was hitting a panic.
Even worse than this, when I then made tests for empty images and tried out the CI, I found that on macos it led to a segmentation fault. This would always be caught, since I think that pointers that don't point anywhere (to zero-sized types) are set to point so some rediculous memory address that tells the operating system/processor to issue a memory page fault, but still it's UB which in the Rust world is *bad*. I raised an [issue with core-foundations-rs](https://github.com/servo/core-foundation-rs/issues/431) where they said the would do an `assert` to check for empty `[u8]`s, but still that would be a panic …

Fix errors when drawing empty image.

---

piet-common/Cargo.toml
piet-common/src/lib.rs
piet/Cargo.toml

If this lands then a follow-up to https://github.com/linebender/druid/pull/1477 could be added to enable serde on kurbo.
It also has a very small drive-by clean up of doc links.

Add a feature "serde" and forward it to kurbo.

---

piet-web/src/text.rs

This matches the behaviour of other backends and fixes a bunch
of broken druid examples.
- closes #366

Always include LineMetric for line 0

---

piet/src/color.rs

This will make these methods harder to misuse.
- closes #371

Color constructors take f64 instead of impl Into<f64>

---

piet-cairo/src/lib.rs
piet-common/src/cairo_back.rs
piet-common/src/cg_back.rs
piet-common/src/direct2d_back.rs
piet-common/src/lib.rs
piet-common/src/web_back.rs
piet-common/tests/image.rs
piet-coregraphics/src/lib.rs
piet-direct2d/src/d2d.rs
piet-direct2d/src/lib.rs
piet-svg/src/lib.rs
piet-web/src/lib.rs
piet/src/image.rs
piet/src/null_renderer.rs
piet/src/render_context.rs

Closes #367.
The trait allows you to get an image's size in a cross-platform way.
Also renames `piet_common::Image` to `PietImage` to avoid clash. This is a breaking change, but if we want to add the `Image` trait and make the cross-platform type alias names more consistent, better to do it now than later.

Add `Image` trait.

---

piet/src/color.rs

This code is a bit idiosyncratic because I wanted it to
work in const contexts.
Question: should we have a `FromStr` impl? This might make sense,
but it's not 100% clear since there are any number of ways to
parse a string into a color. Would this cause problems in practice?
- closes #348
reference: https://github.com/linebender/druid/issues/1471

Add Color::from_hex_str for parsing CSS-style colors

---

.github/workflows/snapshot.yml
.gitmodules
piet/Cargo.toml
piet/src/samples/picture_13.rs
piet/src/samples/picture_14.rs

This lets us include the fonts in the snapshots in our package,
which fixes problems when packaging crates that depend on piet.
We can work around that but it feels best to just include these
files.
This is a bit of bookkeeping I've wanted to get done for a while, and is worth doing before a release.

Move snapshots into piet directory

---

piet-cairo/Cargo.toml
piet-cairo/src/text/lines.rs
piet-web/src/text/lines.rs

We had alread bumped web and not noticed the breakage because
we don't actually run any tests; we'd noticed the breakage in
cairo and not bumped.
This standardizes on 0.3 and fixes the breakage by manually
addung the last line if there's no explicit linebreak.
This should address https://github.com/linebender/druid/issues/1488

Update cairo/web to xi-unicode 0.3

---

piet/src/image.rs

This got lost when `ImageBuf` got moved from `druid-shell`.

re-add Send + Sync to dyn Error.

---

piet/src/image.rs

- this method will be used to implement the Data trait in druid for ImageBuf like this:
```rust
impl Data for ImageBuf {
fn same(&self, other: &Self) -> bool {
self.ptr_eq(other)
}
}
```

This adds a ptr_eq method for ImageBuf

---

piet-direct2d/src/conv.rs
piet-direct2d/src/d2d.rs
piet-direct2d/src/lib.rs
piet-svg/src/lib.rs
piet/Cargo.toml
piet/src/samples/picture_6.rs

This PR adds support for [this Kurbo patch](https://github.com/linebender/kurbo/pull/166). This PR points directly at my Kurbo fork, so it probably shouldn't be merged until the Kurbo PR is merged and a new Kurbo version is published.
`piet-coregraphics` and `piet-cairo` both get this feature for free, because both platforms use paths for rounded rectangles. I have tested both platforms and verified this.
`piet-web` should get this feature for free as well, for the same reason. I have not explicitly tested this, but I feel confident about it since `to_path` is well-tested and is not platform-specific, and RoundedRect is not mentioned in the code.
In `piet-svg`, this has been implemented by simply using a bezier curve if the corner radii aren't all equal, and a rounded rectangle if they …

Support individual corner radii for kurbo::RoundedRect

---

piet/src/color.rs

Fully transparent color is useful, e.g. clearing out certain areas of pixels

Fully transparent color

---

piet-common/Cargo.toml
piet-coregraphics/Cargo.toml

There is an issue on core-graphics backend that RenderContext.blurred_rect can cause memory leak because of an issue that was fixed by https://github.com/servo/core-foundation-rs/commit/dc588497db727a3ba943aaecc83d2a07dc6d6b0a

bump core-graphics to 0.22.2

---

piet-cairo/src/lib.rs
piet-common/examples/png.rs
piet-coregraphics/src/lib.rs
piet-direct2d/src/d2d.rs
piet-direct2d/src/lib.rs
piet-svg/src/lib.rs
piet-web/src/lib.rs
piet/src/null_renderer.rs
piet/src/render_context.rs
piet/src/samples/mod.rs
piet/src/samples/picture_0.rs
piet/src/samples/picture_1.rs
piet/src/samples/picture_10.rs
piet/src/samples/picture_11.rs
piet/src/samples/picture_12.rs
piet/src/samples/picture_13.rs
piet/src/samples/picture_14.rs
piet/src/samples/picture_15.rs
piet/src/samples/picture_2.rs
piet/src/samples/picture_3.rs
piet/src/samples/picture_4.rs
piet/src/samples/picture_5.rs
piet/src/samples/picture_6.rs
piet/src/samples/picture_7.rs
piet/src/samples/picture_8.rs
piet/src/samples/picture_9.rs

This is a working branch for upcoming changes to the `RenderContext::clear` method.
The implementations in this first patch are not expected to be correct. We will figure out a good test case before merging.
The expected behaviour of `clear`:
- completely replace the contents of the buffer specified by the provided region with the provided color.
- if the provided region is `None`, the clear applies to the entire canvas.
- ignore any applied transforms or clipping masks
- when returning from this method, any applied transforms or clipping masks should be restored.

Change clear signature, do preliminary impl work

---

piet-common/tests/text.rs
piet-coregraphics/src/ct_helpers.rs
piet-coregraphics/src/text.rs

It turns out that the width reported by CTLineGetTypographicBounds
*includes* whitespace width; it is just excluded from the size
returned by CTFramesetterSuggestFrameSizeWithConstraints.

[cg] Fix incorrect handling of whitespace width

---

piet-common/src/direct2d_back.rs
piet-direct2d/examples/test-picture.rs
piet-direct2d/src/lib.rs

This will allow users (such as druid) to reuse a given D2DText
object across the multiple render contexts, allow them to share
loaded fonts.
This will let us fix https://github.com/linebender/druid/issues/1622

[d2d] D2DRenderContext takes D2DText object at construction

---

piet-direct2d/src/text.rs

And then checks the system collection afterwards.
- closes #405

[d2d] Text::font_family checks loaded fonts first

---

piet-coregraphics/src/ct_helpers.rs
piet-coregraphics/src/text.rs

The CTLineGetStringRange function I was using for string
ranges apparently doesn't include the range of all trailing
whitespace. This seems to maybe only be a problem for tabs?
In any case, it means we were getting subtly wrong reported
line ranges, which I bumped into with IME.
This fixes that, but just using the start offsets of lines;
we assume a line is the range between two line starts.

[cg] Fix incorrect line ranges with trailing tabs

---

piet-cairo/examples/test-picture.rs
piet-coregraphics/examples/test-picture.rs
piet-direct2d/examples/test-picture.rs
piet/src/samples/mod.rs

The linux CI image has changed, which has caused some breakage with the snapshots; this updates the snapshots and also now tries to record the version of `pango` used if we're on linux. (This requires `apt-cache`, so may only work on debian-based systems? In any case, that is enough for our needs.)

Fixup snapshots

---

piet-common/tests/text.rs
piet/src/text.rs

This was motivated by the pango work; I realized that the
behaviour in the case of interior bytes was not well defined.
This adds checks to ensure backends panic when the provided
index is not a codepoint boundary, and notes that behaviour
may vary if the index is not a grapheme boundary, because
this is not a case I feel compelled to support.

Clarify and test behaviour of hit_test_position

---

piet-common/tests/text.rs
piet/src/text.rs

Because we lack affinity, we can't explicitly request
that the trailing hit be upstream, and the downstream
width is the same as our starting width, leading to
a zero-width rect.
This should fix the issue with weird missing lines in selections (reported on zulip, and discussed in https://github.com/linebender/piet/issues/323#issuecomment-793049972)

Fix incorrect selection rects when emergency breaking

---

piet-cairo/src/lib.rs
piet-coregraphics/src/lib.rs
piet-direct2d/src/conv.rs
piet-svg/src/lib.rs
piet-web/src/lib.rs
piet/src/samples/picture_3.rs
piet/src/samples/picture_6.rs
piet/src/shapes.rs

This started out as my just wanting to fix #416 while it was
on my mind, and then, well, things got a little out of hand.
I realized I wasn't familiar with some of the terminology used,
so I patched up the docs based on the postscript manual. Then
I noticed there were a few areas where the API seemed confusing,
and where the backends had to duplicate a bunch of code in order
to set defaults, so I went through and implemented `Default`,
using the defaults mentioned in the spec.
Highlights:
- 'dash' is replaced with separate 'dash_pattern' and 'dash_offset'
methods
- StrokeStyle can now be constructed in a const context
- dash pattern can now be represented with a static &[f64] slice
- miter limit is now a member of the LineJoin::Miter variant.
- LineCap::Square is replaced with …

Rework the StrokeStyle type

---

piet-cairo/src/lib.rs
piet-common/src/cairo_back.rs
piet-common/src/cg_back.rs
piet-common/src/direct2d_back.rs
piet-common/src/web_back.rs
piet-svg/src/lib.rs
piet-web/src/lib.rs
piet-web/src/text.rs
piet/src/error.rs

This tries to better differentiate three possible error conditions:
when something is impossible, when something is unimplemented,
and when something requires a missing cargo feature.

Clarify and rename some error types

---

piet-svg/src/lib.rs
piet/src/color.rs
piet/src/conv.rs
piet/src/font.rs
piet/src/gradient.rs
piet/src/lib.rs
piet/src/null_renderer.rs
piet/src/render_context.rs
piet/src/shapes.rs
piet/src/text.rs
piet/src/util.rs

This also adds docs or explicit #[allow(missing_docs)] as
appropriate, and a few small, related fixups.

Warn on missing docs and broken doc links

---

piet-svg/src/lib.rs
piet/src/shapes.rs

This is all about ergonomics. I have two goals: to allow
StrokeStyle to be created in a const context, and to make
StrokeStyle cheaply cloneable.
This was a *giant headache*. I tried a Cow, but that didn't work,
because you can't set it in a const context, because it might
call a destructor.
This solution hacks around that. We have separate fields for the
const and non-const case; the non-const case overrides the const
case, but in practice they are unlikely to be used together.

Rework dash representation in StrokeStyle

---

piet/src/lib.rs
piet/src/render_context.rs

It was pointed out on zulip that the docs for `create_image` are
not especially helpful; I fixed up some other stuff while I was
in there.

Improve RenderContext docs

---

piet-cairo/src/text.rs

It seems that the index argument expected here is relative to the start of the text, not the start of the line. Prior to this change long lines w/trailing whitespace would not correctly affect the widest whitespaceless width as their whitespace start index would index past the first line and into part of the second line resulting in a significantly smaller value.
Addresses https://github.com/linebender/druid/issues/1753

Use absolute index to get whitespaceless width & don't sub x coord

---

piet/src/color.rs
piet/src/gradient.rs

Implement Hash and Eq traits on gradient stops, which implies doing the
same for colors. This facilitates creating a cache of baked gradient
ramps.
Closes #450

Make gradient stops hashable

---

piet-cairo/src/lib.rs

Cairo defines pixels as "a 32-bit quantity [...] stored in
native-endian". However, the existing code was treating a pixel as four
8-bit quantities. Put differently, it was hardcoding little endian.
This commit changes the code to first calculate the pixel value as an
u32 and then use u32::to_ne_bytes() to get back to "the world of bytes".
For readability, this is done in a new helper function.
I did not actually check if this fixes anything on big endian, but at
least it does not change anything for little endian according to the
test-pictures examples.
Fixes: https://github.com/linebender/piet/issues/224
Signed-off-by: Uli Schlachter <psychon@znc.in>

[cairo] Fix for big-endian systems

---

piet-cairo/Cargo.toml
piet-cairo/benches/make_image.rs

This adds a simple benchmark for piet-cairo's make_image function.
Signed-off-by: Uli Schlachter <psychon@znc.in>
----
Here is the output when I run this locally (`cargo bench`):
```
Running /tmp/piet/target/release/deps/make_image-e4985702849e1350
WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.
make_image_2160p_Grayscale                                                                            
time:   [35.601 ms 35.607 ms 35.614 ms]
Found 2 outliers among 100 measurements …
```

[cairo] Add a simple criterion benchmark

---

piet/src/render_context.rs

The image format is based on individual bytes and thus independent of
the system's endianness. This commit tries to make that more explicit.
This was originally suggested in issue #224.
Signed-off-by: Uli Schlachter <psychon@znc.in>

Try to clarify docs for ImageFormat

---

piet-cairo/src/lib.rs
piet-direct2d/src/conv.rs
piet-direct2d/src/text.rs
piet-svg/src/lib.rs
piet-web/src/lib.rs
piet/src/shapes.rs

These were marked as deprecated in 0.4.1 and can now be removed.

Remove deprecations

---

piet-cairo/README.md
piet-cairo/src/text.rs
piet-common/Cargo.toml
piet-common/README.md
piet-common/src/lib.rs

The cairo backend works without any platform specific modifications,
just like on Linux.

Build on OpenBSD

---

piet-common/src/cairo_back.rs
piet-common/src/cg_back.rs
piet-common/src/direct2d_back.rs

Currently, calling either of these functions will simply return `Error::NotSupported`
without any further explanation. This can lead one to believe that the function itself
is not supported on a given platform, rather than just the `ImageFormat`.
This change clarifies that this is the caller's responsibility in the documentation.

Add warning about ImageFormat and backend compat

---

piet-coregraphics/Cargo.toml
piet-coregraphics/src/text.rs

This implements caching of `CTFont` handles, not unlike the current font-family cache. This solves a real bottleneck I have in Psst (where creating lot of labels used to be really slow). I've used the `associative-cache` crate, because it is used in the Direct2D backend already (for caching gradients), and also switched the font family cache to it, for consistency.
Thanks!

Cache CTFont handles on macOS

---

piet/src/lib.rs

Currently there is no direct link to `piet-common`'s documentation from
the main docs page, and that is quite annoying to navigate if you're
referencing both a lot.
This adds that, along with some newbie guidance for how to create
`RenderContext`s for those who are getting started.

Add piet-common reference to main documentation

---

piet-svg/Cargo.toml
piet-svg/examples/basic-svg.rs
piet-svg/src/evcxr.rs
piet-svg/src/lib.rs
piet-svg/src/text.rs
piet/src/lib.rs
piet/src/samples/mod.rs

The tricky bit is text layout sizing, which I need for my use-case (drawing graphs in svg using piet).  I've taken the approach of loading the font on the host machine, then doing a shaping run with `rustybuzz` and then calculating the dimensions of the run. It doesn't work perfectly but it's OK on my machine. I thought there would be an issue with DPI, but it seems that the SVG renderer (I'm using Firefox) operates at the standard DPI and then scales everything up, so there's no issue. Named font sizing works better than using `sans-serif` or `system-ui`, presumably because font-kit and Firefox differ in their opinion of what the default sans-serif font is.
Anyway I'm PRing this because although it is not perfect, it is a significant improvement on what is currently there (nothing). I'm …

Implement text and bitmap images in piet-svg

---

piet-common/Cargo.toml
piet-common/src/lib.rs

Confirmed text drawing and simple shapes work on iOS:

Add iOS as a CoreGraphics operating system to piet-common

---

piet/src/text.rs

Issue #483  (extended, conflict with PR #484) 
The PR adds  `Debug`, `Clone` and `PartialEq` derives to `TextAttribute`.

feat(piet): add Debug,Clone,PartialEq impls to TextAttribute

---

piet-cairo/Cargo.toml
piet-cairo/src/text.rs
piet-common/Cargo.toml

- Remove unused `glib` and `pango-sys` deps for `piet-cairo`.
- Update for specific attribute types `pango` now exports for `piet-cairo`.
- Use `AttrInt::new_insert_hyphens` removing unnecessary `unsafe` for `piet-cairo`.

Update GTK deps

---

README.md
piet/src/samples/picture_13.rs

The problem here is that `include_bytes` runs at compile time, and it doesn't seem to matter what features are enabled? So I suspect this problem will pop up fairly often.
I don't want to spend the time to try and figure out a real solution right now (although someone else is welcome to!) but this at least mentions the problem in the README, and adds a comment inline that will be printed whenever this problem is encountered. Maybe someone will even see it?
```
error: couldn't read piet/src/samples/../../snapshots/resources/Anaheim-Regular.ttf: No such file or directory (os error 2)
--> piet/src/samples/picture_13.rs:16:28
|
16 |       let _ = text.load_font(include_bytes!(
|  ____________________________^
17 | |         "../../snapshots/resources/Anaheim-Regular.ttf"
18 | |     )); // …
```

Mention submodules in readme & at likely error site

---

piet-cairo/src/text.rs

This comment used to point out unneeded `unsafe` which has been removed.
On a side note, I had a look at the hacks for RTL and it doesn't look like the original problem has been fixed yet (tested with pango `1.50.3`). I did start going down the path of fixing pango, but I need to find some more time for that task as it is a bit more convoluted than I thought it would be. I'll make a PR if I do get around to fixing it.

Remove unspecific comment

---

piet-coregraphics/src/text.rs
piet-direct2d/src/text.rs
piet-direct2d/src/text/lines.rs
piet-web/src/text/grapheme.rs

These are slightly weird, but basically clippy now uses a heuristic to
identify certain method calls that it expects to be resolve to a field
access, and flags that these do not need to be wrapped in closures:
https://github.com/rust-lang/rust-clippy/issues/8109#issuecomment-991964291

Fixup new clippy lints

---

piet-svg/src/lib.rs

Unless I misread how piet works, I think there was a missing apply of the transform and clip path when drawing an image. This should fix it. :)

piet-svg: fix missing transform, clip when drawing image

---

piet-cairo/examples/test-picture.rs
piet-coregraphics/examples/test-picture.rs
piet-direct2d/examples/test-picture.rs
piet/src/samples/picture_0.rs
piet/src/samples/picture_1.rs
piet/src/samples/picture_10.rs
piet/src/samples/picture_11.rs
piet/src/samples/picture_12.rs
piet/src/samples/picture_13.rs
piet/src/samples/picture_14.rs
piet/src/samples/picture_15.rs
piet/src/samples/picture_2.rs
piet/src/samples/picture_3.rs
piet/src/samples/picture_4.rs
piet/src/samples/picture_5.rs
piet/src/samples/picture_6.rs
piet/src/samples/picture_7.rs
piet/src/samples/picture_8.rs
piet/src/samples/picture_9.rs

The current test image code has a constant size which is hardcoded to expect a scale factor of `2.0`.
This PR changes the test image code to specify the logical size that the code actually uses, and then the platform code that actually generates the image and chooses the scale factor will also choose the proper image size.
Results remain unchanged for the scale factor of `2.0` but this reduces confusion and helps enable a future potential of doing snapshot testing with multiple different scale factors.

Improve test image scale support.

---

piet-cairo/Cargo.toml
piet-cairo/examples/test-picture.rs
piet-common/src/cairo_back.rs
piet-common/src/cg_back.rs
piet-common/src/direct2d_back.rs
piet-coregraphics/Cargo.toml
piet-coregraphics/examples/test-picture.rs
piet-coregraphics/src/lib.rs
piet-direct2d/Cargo.toml
piet-direct2d/examples/test-picture.rs
piet/src/util.rs

Currently the `test-picuture` example projects for Direct2D/CoreGraphics/Cairo are very bespoke.
The code is brittle and not as widely tested. My motivation for doing this refactoring comes from finding out that the CoreGraphics test picture code has no understanding of stride. Yet it gives `0` (which means automatic) as the stride to `CGBitmapContextCreate`, so macOS decides.
Running tests on my macOS 10.15.4 with sample picture `0` (which has a width of `200dp`) gave me the following results:
| Scale | Expected | Actual |
|-------|----------|--------|
| 1.0   | 800      | 832    |
| 1.5   | 1200     | 1216   |
| 2.0   | 1600     | 1600   |
| 2.5   | 2000     | 2048   |
As you can see, the faulty logic is invisible at a scale ratio of `2.0` but causes an assert failure with other scales, …

Refactor the test picture generator

---

piet-common/src/cg_back.rs

#196 added stride support which is great, but the pixel byte order swapping introduced there seems wrong.
1) In the fast path, when the whole stride is used, the code just copies bytes. However when the stride is longer, blue and red are swapped. This seems highly suspicious by itself already. Why would the pixel format depend on the stride length? In my testing, it doesn't.
2) As I discovered during my work in [#520](https://github.com/linebender/piet/pull/520), macOS gives us a fully utilized stride with our current test code. So the pixel swaping code never runs with our test images. The bug is hidden.
3) Changing `SCALE` in `test-picture.rs` to something else like `1.0` causes the output test image to have blue and red swapped. Confirming the bug.
Thus I have modified the code to keep …

Fix CoreGraphics copy_raw_pixels swaping red and blue channels.

---

piet-cairo/examples/test-picture.rs
piet/src/gradient.rs
piet/src/image.rs

This PR addresses the following clippy lints:
* [`extra_unused_lifetimes`](https://rust-lang.github.io/rust-clippy/master/index.html#extra_unused_lifetimes)
* [`map_identity`](https://rust-lang.github.io/rust-clippy/master/index.html#map_identity)
* [`format_push_string`](https://rust-lang.github.io/rust-clippy/master/index.html#format_push_string)

Satisfy clippy 1.62

---

.github/workflows/snapshot.yml
piet-cairo/examples/test-picture.rs
piet-coregraphics/examples/test-picture.rs
piet-direct2d/examples/test-picture.rs
piet/src/samples/mod.rs

This PR further generalizes the test picture code by making it much more scale-aware. It is now possible to specify a `--scale 5` option at runtime to get the test pictures at 500% scale. The generated filenames now contain the scale information and the comparison functions are aware of this.
Additionally I also updated the snapshots testing configuration to do the tests at both 1x and 2x scale. While reviewing #513 I've found that this points out weird behavior that would go unnoticed with just the old 2x scale testing.

Add runtime scale configuration to the test picture generator.

---

piet-cairo/src/lib.rs
piet-coregraphics/src/lib.rs
piet-direct2d/src/conv.rs
piet-direct2d/src/d2d.rs
piet-direct2d/src/lib.rs
piet/src/samples/mod.rs
piet/src/samples/picture_16.rs

The `capture_image_area` method of the CoreGraphicsContext was not
taking into account that a transformation matrix is applied to the
context. As a result, it only worked correctly if one applied this
scaling manually to the `src_rect` prior to passing it to the method.
With this addition, we now respect the CG transformation matrix and
apply it to the `src_rect` prior to cropping the captured `CGImage`.

Fix `capture_image_area` not respecting CG transformation matrix

---

piet-common/examples/mondrian.rs
piet-coregraphics/src/ct_helpers.rs
piet-coregraphics/src/gradient.rs
piet-coregraphics/src/lib.rs
piet-coregraphics/src/text.rs
piet-direct2d/src/conv.rs
piet-direct2d/src/text.rs
piet-svg/src/lib.rs
piet-web/src/lib.rs
piet-web/src/text.rs
piet/src/color.rs

A small patch that derives the `Copy` trait for `Color` making it more convenient to use as a value and also permits embedding it in other `Copy` structures.

Derive `Copy` for `Color`

---

piet-web/src/lib.rs
piet/src/color.rs
piet/src/render_context.rs
piet/src/shapes.rs
piet/src/text.rs

This PR addresses the following clippy lints:
* [`borrow_deref_ref`](https://rust-lang.github.io/rust-clippy/master/index.html#borrow_deref_ref)
* [`derive_partial_eq_without_eq`](https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq)
The `PartialEq` without `Eq` lint seems somewhat slippery in general, because we might want to expand a type with floats or such in the future. However in the specific cases here I think it's fine.

Satisfy clippy 1.63

---

piet-cairo/README.md
piet-common/Cargo.toml
piet-common/README.md
piet-common/src/lib.rs

The following changes allow `piet` to build on NetBSD.
```
> uname -a
NetBSD mybox 9.99.101 NetBSD 9.99.101 (GENERIC) #0: Tue Oct 11 15:59:38 UTC 2022  mkrepro@mkrepro.NetBSD.org:/usr/src/sys/arch/amd64/compile/GENERIC amd64
> cargo build --release
Compiling proc-macro2 v1.0.47
Compiling quote v1.0.21
Compiling unicode-ident v1.0.5
Compiling pkg-config v0.3.25
Compiling syn v1.0.102
Compiling serde v1.0.145
Compiling heck v0.4.0
Compiling smallvec v1.10.0
Compiling thiserror v1.0.37
Compiling autocfg v1.1.0
Compiling version-compare v0.1.0
Compiling libc v0.2.135
Compiling log v0.4.17
Compiling cfg-if v1.0.0
Compiling once_cell v1.15.0
Compiling bitflags v1.3.2
Compiling version_check v0.9.4
Compiling cc v1.0.73
Compiling wasm-bindgen-shared v0.2.83
Compiling crc32fast v1.3.2
Compiling …
```

Add support for NetBSD

---

piet-web/src/lib.rs

I implemented the  `TODO(performance)`.
It's hard to tell if there is really a big performance increase, but there is definitely less calls to the Canvas API.

Optimized set_stroke for piet_web

---

piet-cairo/src/lib.rs
piet-svg/src/lib.rs
piet-svg/src/text.rs

Because SVG uses the baseline to position text, while we use the
top-left of the text, we need to convert between the two.
Before this PR, the whole font height was used, which pushes the text
down too far.
After this PR, we tell SVG to use the top of the ascender as our anchor
point (`dominant-baseline: hanging`), with an additional fiddle factor
of 0.04 * font height because we actually want the top of the line, not
the ascender. The fiddle factor was worked out by eye looking at the
default sans-serif font, comparing the svg to a png generated by
piet-cairo.

Improve text position in SVG.

---

piet-coregraphics/src/lib.rs

CoreGraphicsContext::draw_image_area() doesn't account for coregraphics' reversed y-axis, 086e8e613dfc951f869b6f6ebb9ebcba012ab25a fixes that by passing the cropped image to CoreGraphicsContext::draw_image() which does draw correctly.

Improve piet-coregraphics

---

piet-direct2d/src/d2d.rs
piet-direct2d/src/lib.rs

Using capture_image_area on a druid paint context currently fails on windows/direct2d for the following reasons:
1) Druid paint contexts have layer masks applied to the render context, which causes the call to [ID2D1Bitmap::CopyFromRenderTarget](https://docs.microsoft.com/en-us/windows/win32/api/d2d1/nf-d2d1-id2d1bitmap-copyfromrendertarget) to fail.
2) Druid's internal surface format is BGRA and piet_direct2d::D2DRenderContext::create_blank_bitmap hardcoded RGBA, which also causes the call to ID2D1Bitmap::CopyFromRenderTarget to fail.
This PR fixes the above two issues so that capture_image_area works inside druid widget paint loops. The caveat is that as the returned image format now matches the druid surface format, you can receive captured images which are not RGBA. That's not an …

Modify capture_image_area to work with druid direct2d surfaces

---

piet-cairo/Cargo.toml
piet-cairo/src/lib.rs
piet-cairo/src/text.rs
piet-common/Cargo.toml

this updates the cairo and pango dependencies to the newest versions.
There were not a lot of API changes: some struct fields were changed to private visibility and now have getter methods, and some structs now need to be created through `new()` functions.

update cairo and pango to v0.16

---

.github/workflows/ci.yml
piet-cairo/Cargo.toml
piet-common/Cargo.toml
piet-coregraphics/Cargo.toml
piet-direct2d/Cargo.toml
piet-svg/Cargo.toml
piet-web/Cargo.toml
piet-web/examples/basic/Cargo.toml
piet/Cargo.toml

This is a rebase of #518, bumping all the versions to 0.6.0.

Bump version to 0.6.0

---

piet-cairo/src/text.rs
piet-common/src/cg_back.rs
piet-common/src/web_back.rs
piet-direct2d/src/dwrite.rs
piet-web/src/text.rs
piet/src/color.rs
piet/src/font.rs
piet/src/samples/mod.rs

This PR addresses the following clippy lints:
* [`manual_clamp`](https://rust-lang.github.io/rust-clippy/master/index.html#manual_clamp)
* [`needless_borrow`](https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow)
* [`unnecessary_cast`](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast)

Satisfy clippy 1.66

---

piet-coregraphics/Cargo.toml
piet-direct2d/Cargo.toml

Adds [`docs.rs` metadata](https://docs.rs/about/metadata) instructions.
I haven't tested if this is enough to actually build, but considering that [`winapi`](https://docs.rs/crate/winapi/latest/source/Cargo.toml), `win-rs` and [`core-x`](https://docs.rs/crate/core-foundation/0.9.3/source/Cargo.toml) are doing this, it should work.

Fix `docs.rs` generation by building on Windows for D2D and on Mac for Coregraphics

---

piet-cairo/benches/make_image.rs
piet-cairo/examples/test-picture.rs
piet-common/tests/text.rs
piet-direct2d/src/d2d.rs
piet-direct2d/src/dwrite.rs
piet-direct2d/src/lib.rs
piet-direct2d/src/text.rs
piet-web/src/text.rs
piet/src/color.rs
piet/src/error.rs
piet/src/samples/mod.rs

Clippy lints addressed:
* [`uninlined_format_args`](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args)

Satisfy clippy 1.67 beta

---

piet/src/font.rs
piet/src/gradient.rs
piet/src/image.rs
piet/src/render_context.rs
piet/src/shapes.rs
piet/src/text.rs

Some links were broken while others were not. I converted all of them to symbol based links to fix the broken ones and hopefully keep all of them functioning for longer.
The only exceptions were `StrokeStyle#structfield.dash_offset` and `StrokeStyle#structfield.dash_pattern` which keep the URL fragment part. Apparently rustdoc has no way to [disambiguate](https://doc.rust-lang.org/rustdoc/write-documentation/linking-to-items-by-name.html#namespaces-and-disambiguators) struct fields. There are ways to disambiguate other stuff like methods, but not fields. Fields were mentioned as [a potential future extension](https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md#linking-to-fields) in the RFC, but that work hasn't happened as far as I can tell.

Convert doc links to symbols.

---

piet-cairo/Cargo.toml
piet-common/Cargo.toml
piet-coregraphics/Cargo.toml
piet-direct2d/Cargo.toml
piet-svg/Cargo.toml
piet-web/Cargo.toml
piet-web/examples/basic/Cargo.toml
piet/Cargo.toml

This PR does two things:
These are all semver compatible changes. These are versions that Cargo resolves to anyway, which also means they're the versions we actually test with. For the curious I've written more about the rationale for doing this in the Druid [CONTRIBUTING.md](https://github.com/linebender/druid/blob/master/CONTRIBUTING.md#dependencies).
The main reason for doing the release is the merger of #546 and #548. Both of them address issues with Piet's documentation. A new release gets us a better docs.rs page and also helps with Druid 0.8 docs as Piet is embedded there.

Prepeare for releasing v0.6.1

---

piet-cairo/Cargo.toml
piet-common/Cargo.toml
piet-common/src/lib.rs
piet-coregraphics/Cargo.toml
piet-direct2d/Cargo.toml
piet-svg/Cargo.toml
piet-web/Cargo.toml
piet/Cargo.toml
piet/src/lib.rs

Druid v0.8 ended up shipping with a different major version of `image` than Piet, which causes severe issues due to their incompatibility. The ultimate solution to this is to just have Piet re-export the `image` crate and `druid-shell` depend on that. Synchronization bliss!
This PR re-exports the `image` crate and bumps the version to v0.6.2.

Re-export the `image` crate and prepare v0.6.2.

---

piet-cairo/Cargo.toml
piet-common/Cargo.toml

This PR updates the cairo, pango & pangocairo dependencies in piet-cairo to the latest version: v0.17

Bump cairo, pango, pangocairo to v0.17

---

piet/src/font.rs
piet/src/shapes.rs
piet/src/text.rs

Clippy lints addressed:
* [`derivable_impls`](https://rust-lang.github.io/rust-clippy/master/index.html#derivable_impls)

Satisfy clippy 1.68.

---

piet-cairo/src/lib.rs
piet-coregraphics/src/lib.rs
piet-direct2d/src/lib.rs
piet-svg/src/lib.rs
piet-web/src/lib.rs
piet/src/null_renderer.rs
piet/src/render_context.rs
piet/src/util.rs

The `make_image_with_stride` function will allow to create images from a buffer with a specific row stride. See #553 for more info.
Progress:
Resolves #553.

Add `make_image_with_stride`

---

piet/src/samples/mod.rs

I'm currently using a [hacky workaround](https://github.com/notgull/piet-hardware/blob/9bb5e1cdf58bdc8ad47fd7ea3906fbc72da9a034/crates/piet-wgpu/examples/test_picture_wgpu.rs#L46-L69) in `piet-hardware` to test samples, and it doesn't look like there is a reason why it's an `fn` pointer instead of an `Fn` trait?

Make samples_main take an Fn trait

---

piet-cairo/Cargo.toml
piet-common/Cargo.toml
piet-web/src/lib.rs

A new pango and cairo release is out, the changelog can be found [here](https://github.com/gtk-rs/gtk-rs-core/releases/tag/0.18.0). There are no changes in the API that are used by piet as far as I can tell.
Can there be a new piet release at some point? The last one is using cairo v0.16 .

Bump pango, cairo to v0.18

---

piet/src/color.rs

similar to `with_alpha()`, which unfortunately can't currently be `const fn` due to floating point arithmetic's, I am suggesting to add `const fn with_a8()`.
My personal use case for it: I have a palette of predefined colors (think Gnome Colors), which I use as the basis for other default colors definitions (which is why I need 'const' ).
Related: [the discussion](https://github.com/linebender/piet/pull/524) that Color probably won't be anything else than u32 so the `const` is unlikely to become a problem in the future.
With the same thought, `as_rgba_u32()` can then also converted to be const.
I could also add analogous methods `with_r8()`, `with_g8()` and `with_b8()` to the PR for completeness sake, if the idea is approved.

adding const fn with_a8() to Color

---

piet-coregraphics/src/text.rs
piet-direct2d/src/lib.rs
piet-svg/Cargo.toml
piet-svg/src/text.rs
piet/Cargo.toml

This updates to the latest kurbo, I could have a version which is compatible with both piet and vello... 
* Svg had a future incompatibility warning, upgrade to fix that.
* Clippy noticed that `font_kit::sources::MultiSource` is `!Send !Sync`, So replace `Arc<Mutex<MultiSource>` with `Rc<RefCell<_>>`.
Not sure if this last bit is a wanted change, or if it'd be preferred to just silence the warning, or ignore it entirely?

Update kurbo and svg dependencies, fix a clippy warning.

---

piet-cairo/Cargo.toml
piet-cairo/src/lib.rs
piet-common/Cargo.toml
piet-direct2d/src/text.rs
piet-web/src/text.rs

Updates to the just released versions of pango and cairo (v0.19)
(and satisfy clippy)

Bump versions of pango, cairo

---

.github/workflows/ci.yml
piet-common/Cargo.toml
piet-common/src/direct2d_back.rs
piet-direct2d/Cargo.toml
piet-direct2d/src/d2d.rs
piet-direct2d/src/dwrite.rs
piet-direct2d/src/text.rs
piet-web/src/lib.rs
piet-web/src/text.rs
piet/src/text.rs

* Update Rust stable to 1.82.
* Satisfy Clippy 1.82.
* Update snapshots to reflect the CI macOS 14.7.0 behavior. ([piet-snapshots#35](https://github.com/linebender/piet-snapshots/pull/35))
* Disable Firefox testing on macOS as the new macOS 14 runners don't have Firefox installed.

Fix all CI failures.

---

piet-cairo/Cargo.toml
piet-cairo/src/lib.rs
piet-common/Cargo.toml
piet-direct2d/src/lib.rs
piet/Cargo.toml

Simply bumping the versions seems to be enough, there are no API updates that would require any changes in piet this time (see changelog [here](https://github.com/gtk-rs/gtk-rs-core/releases/tag/0.20.0))

Bump versions of kurbo,cairo, pango deps

---

README.md

The `test-picture` example is per backend and can't be run from the workspace root, unless the manifest is specified. Easier alternative is to run the command from the specific backend's directory.
Fixes #570.

Clarify how to run examples.

---

piet-web/Cargo.toml

The `console` feature was only enabled with dev dependencies.
That combined with the Piet CI being of an older Linebender variation that tests with dev dependencies enabled means that the CI didn't catch that `piet-web` can't actually be compiled.

Enable the console feature for web-sys.

---

CONTRIBUTING.md
README.md

Now that the `master` branch is called `main` a few docs needed updating. A badge needed updating too, so I updated the whole set to a newer standard.

Update readme badges and `main` branch references.

---

.github/workflows/ci.yml

The per-platform exclusions were getting a bit crazy, with a lot of step duplication. This new approach uses a JSON object with dynamic access to reduce the number of steps back down to sanity.

Simplify per-platform package exclusion in CI.

---

Cargo.toml
piet-cairo/Cargo.toml
piet-coregraphics/Cargo.toml
piet-direct2d/Cargo.toml

We use `piet-common` only as a dev-dependency, so we can get away with not specifying a version. This helps resolve a cyclical dependency issue when publishing, where e.g. `piet-cairo` depends on `piet-common` which depends on `piet-cairo`.

Resolve cyclical `piet-common` dependency.
