linebender/piet

- piet-cairo/examples/basic-cairo.rs
- piet-cairo/src/lib.rs
- piet-direct2d/examples/basic.rs
- piet-direct2d/src/lib.rs
- piet-web/Cargo.toml
- piet-web/examples/basic/src/lib.rs
- piet-web/src/lib.rs
- piet/src/text.rs
This adds text width measurement, and is a reasonably quick followup to #5, but I thought it might be useful to have it as a separate PR.
> Text width

- piet-cairo/examples/basic-cairo.rs
- piet-direct2d/examples/basic.rs
- piet-test/src/lib.rs
- piet-test/src/picture_0.rs
- piet-test/src/picture_1.rs
- piet-web/examples/basic/src/lib.rs
I was playing around with kurbo and decided to add a new example.
> Add a new example

- .travis.yml
> Windows CI

- piet-web/README.md
- piet-web/examples/basic/basic-web-static/dist/.gitignore
- piet-web/examples/basic/build.sh
> Switch to using wasm-pack

- piet-cairo/src/lib.rs
- piet-common/examples/png.rs
- piet-direct2d/src/lib.rs
- piet-test/src/picture_0.rs
- piet-test/src/picture_1.rs
- piet-test/src/picture_2.rs
- piet-test/src/picture_3.rs
- piet-web/src/lib.rs
- piet/src/render_context.rs
Reduce the amount of error checking that's necessary.
Closes #34
> Defer errors

- piet-cairo/src/lib.rs
- piet-direct2d/src/conv.rs
- piet-direct2d/src/lib.rs
- piet-test/src/lib.rs
- piet-test/src/picture_4.rs
- piet-web/Cargo.toml
- piet-web/src/lib.rs
- piet/src/gradient.rs
- piet/src/lib.rs
- piet/src/render_context.rs
Implementations for all 3 back-ends, with very basic testing in picture_4.
> Add gradients

- piet-cairo/Cargo.toml
- piet-common/Cargo.toml
- piet-direct2d/Cargo.toml
- piet-test/Cargo.toml
- piet-web/Cargo.toml
- piet-web/examples/basic/Cargo.toml
- piet/Cargo.toml
In preparation for crates.io release. Also bump kurbo.
> Set version to 0.0.2

- .azure-pipelines.yml
- ci/install-rust.yml
- ci/test.yml
I couldn't get cairo installed on windows, but otherwise this is working? 🤷‍♂
> Setup azure pipelines for ci

- piet-cairo/Cargo.toml
- piet-cairo/src/lib.rs
- piet-common/Cargo.toml
- piet-direct2d/Cargo.toml
- piet-direct2d/src/conv.rs
- piet-direct2d/src/lib.rs
- piet-test/Cargo.toml
- piet-test/src/picture_0.rs
- piet-test/src/picture_1.rs
- piet-test/src/picture_3.rs
- piet-web/Cargo.toml
- piet-web/src/lib.rs
- piet/Cargo.toml
This fixes things changed in kurbo, and bumps manifests for a release.
> Release 0.3

- piet-cairo/Cargo.toml
- piet-common/Cargo.toml
- piet-direct2d/Cargo.toml
- piet-test/Cargo.toml
- piet-test/src/picture_0.rs
- piet-test/src/picture_2.rs
- piet-web/Cargo.toml
- piet/Cargo.toml
This includes the removal of Point & Coord assoc types, and
upstream changes in kurbo.
-----
I'm trying to resist the inclination to sit on releases. I'd like some of these features in druid.
> Bump versions for 0.0.4 release

- .gitignore
- piet-cairo/Cargo.toml
- piet-cairo/examples/basic-cairo.rs
- piet-cairo/src/lib.rs
- piet-common/Cargo.toml
- piet-common/src/cairo_back.rs
- piet-direct2d/Cargo.toml
- piet-test/Cargo.toml
- piet-web/Cargo.toml
- piet/Cargo.toml
This requires minor changes for cairo API tweaks, and also fiddles
with gitignore a bit.
> Bump for release, update cairo & kurbo

- piet-cairo/src/lib.rs
- piet-direct2d/src/lib.rs
- piet-web/src/lib.rs
- piet/src/gradient.rs
- piet/src/null_renderer.rs
- piet/src/render_context.rs
this will conflict with a few inflight PRs, but I don't think there's any benefit to a particular merge order.
> Rename IBrush -> IntoBrush

- piet-cairo/src/lib.rs
- piet-direct2d/src/lib.rs
- piet-web/src/lib.rs
- piet/src/gradient.rs
- piet/src/null_renderer.rs
- piet/src/render_context.rs
This also adds 'from' impls for the two concrete gradient types for
FixedGradient, and clarifies some docs.
> Use impl Into<FixedGradient> in place of concrete type

- piet/src/render_context.rs
This is a concrete type that can be any color or gradient. (And
perhaps in the future an image?)
> Add PaintBrush enum

- piet-cairo/Cargo.toml
- piet-common/Cargo.toml
- piet-direct2d/Cargo.toml
- piet-test/Cargo.toml
- piet-web/Cargo.toml
- piet/Cargo.toml
> Add repository links to Cargo files

- piet-cairo/Cargo.toml
- piet-common/Cargo.toml
- piet-direct2d/Cargo.toml
- piet-test/Cargo.toml
- piet-web/Cargo.toml
- piet/Cargo.toml
- piet/src/gradient.rs
- piet/src/render_context.rs
This also bumps version numbers, although I am not going to
release in a hurry.
> Add a few `Debug, Clone` derives related to PaintBrush

- piet-cairo/Cargo.toml
- piet-common/Cargo.toml
- piet-direct2d/Cargo.toml
- piet-svg/Cargo.toml
- piet-test/Cargo.toml
- piet-web/Cargo.toml
- piet/Cargo.toml
> Bump versions for 0.0.9 release

- piet-direct2d/src/dwrite.rs
This turns out to be incorrect logic in vec capacity.
> Fix crash in textbox

- piet-common/src/direct2d_back.rs
Fixes a crash in https://github.com/xi-editor/druid/pull/499
> Cleanup bitmap_target on drop

- README.md
[Rendered Preview](https://github.com/msiglreith/piet/blob/readme-badges/README.md)
It's just so convenient to have everything in place in the README (:
> Improve README: badges for crates.io and docs.rs

- piet/Cargo.toml
> Update kurbo to 0.5.11.

- piet-cairo/Cargo.toml
- piet-common/Cargo.toml
- piet-direct2d/Cargo.toml
- piet-svg/Cargo.toml
- piet-test/Cargo.toml
- piet-web/Cargo.toml
- piet/Cargo.toml
Preparation for the upcoming release.
> Bump version to 0.0.10.

- piet-cairo/Cargo.toml
- piet-common/Cargo.toml
- piet-direct2d/Cargo.toml
- piet-direct2d/examples/basic.rs
- piet-svg/Cargo.toml
- piet-test/Cargo.toml
- piet-web/Cargo.toml
- piet/Cargo.toml
This PR updates all dependencies and also bumps the piet version to 0.0.11.
> Update dependencies; version to 0.0.11.

- piet-common/examples/png.rs
- piet-common/src/direct2d_back.rs
- piet-direct2d/examples/basic.rs
- piet-direct2d/src/lib.rs
> [d2d] Assert that finish() has happened on drop

- piet/src/samples/mod.rs
This was the result of a collision between #181 and #178.
closes #185
> Fix compilation failure

- piet-direct2d/src/text.rs
- piet/src/lib.rs
- piet/src/util.rs
This is intended for bits of code shared between various backend
implementations.
closes #183
> Add piet::util module

- piet-common/src/cg_back.rs
Apparently we aren't running with this in CI?
> Fix a compilation error with --png feature

- piet-cairo/Cargo.toml
- piet-common/Cargo.toml
- piet-coregraphics/Cargo.toml
- piet-direct2d/Cargo.toml
- piet-svg/Cargo.toml
- piet-web/Cargo.toml
- piet/Cargo.toml
This finally moves us to 0.1.0, which should make it slightly easier
to make bugfix releases etc.
> Update crate versions (0.1.0)

- piet-common/src/cg_back.rs
- piet-coregraphics/src/lib.rs
These were causing the druid tests to fail :(((
> [cg] Fix two issues with images

- piet-common/Cargo.toml
- piet-coregraphics/Cargo.toml
- piet-coregraphics/src/text.rs
- fixes https://github.com/xi-editor/druid/issues/958
> [cg] Fix crash when hit testing empty string

- piet-cairo/src/lib.rs
- piet-cairo/src/text.rs
- piet-common/src/cairo_back.rs
- piet-common/src/cg_back.rs
- piet-common/src/direct2d_back.rs
- piet-common/src/lib.rs
- piet-common/src/web_back.rs
- piet-coregraphics/src/lib.rs
- piet-coregraphics/src/text.rs
- piet-direct2d/examples/basic.rs
- piet-direct2d/src/dwrite.rs
- piet-direct2d/src/lib.rs
- piet-direct2d/src/text.rs
- piet-direct2d/src/text/lines.rs
- piet-svg/src/text.rs
- piet-web/src/lib.rs
- piet-web/src/text.rs
For now I am just experimenting and abusing CI to test stuff I cannot test locally
> Remove lifetime from D2DText

- piet-cairo/Cargo.toml
- piet-common/Cargo.toml
- piet-coregraphics/Cargo.toml
- piet-direct2d/Cargo.toml
- piet-svg/Cargo.toml
- piet-web/Cargo.toml
- piet/Cargo.toml
I want the no lifetime `Text` for my text work.
> Update piet versions

- piet-common/Cargo.toml
> Bump piet-common to 0.2.0

- piet-common/Cargo.toml
- piet-coregraphics/Cargo.toml
- piet-coregraphics/src/ct_helpers.rs
- piet-coregraphics/src/gradient.rs
- piet-coregraphics/src/lib.rs
- piet-coregraphics/src/text.rs
These weren't available when this was first written, but they
let us clean things up quite a bit.
> Use new upstream methods for various core-graphics/text things

- piet-cairo/examples/basic-cairo.rs
- piet-coregraphics/examples/test-picture.rs
- piet-direct2d/examples/basic.rs
- piet/src/lib.rs
- piet/src/samples/mod.rs
- piet/src/samples/picture_0.rs
- piet/src/samples/picture_1.rs
- piet/src/samples/picture_2.rs
- piet/src/samples/picture_3.rs
- piet/src/samples/picture_4.rs
- piet/src/samples/picture_5.rs
- piet/src/samples/picture_6.rs
This is something I've wanted for a while,
and want especially for testing text layouts drawing.
slightly related: the d2d backend's sample drawing code
*terrifies* me.
> Allow sample pictures to specify their size

- piet-direct2d/src/dwrite.rs
DirectWrite uses the provided width and height in some calculations
(such as in the output of DWRITE_OVERHANG_METRICS) and passing
f32::INFINITY produces nonsense values.
This was motivated by #238, where currently  `TextLayout::image_bounds` returns garbage on windows if no width constraint is provided.
> [d2d] Don't pass infinite width constraint to dwrite

- piet-direct2d/src/text/lines.rs
We were confusing ourselves by trying to move between lengths
and offsets, and it's easier to reason about lengths.
Bit of a brain lapse in the original impl, not sure what I was thinking about with the adding and subtracting of offsets. 🤷
> [d2d] Fix utf16 logic error

- piet-cairo/src/text.rs
- piet-cairo/src/text/grapheme.rs
- piet-coregraphics/src/text.rs
- piet-direct2d/src/text.rs
- piet-web/src/text.rs
- piet-web/src/text/grapheme.rs
- piet/src/text.rs
- piet/src/util.rs
This motivated me to also make HitTestPosition and HitTestPoint
be non_exhaustive, which resulted in a minor refactor.
> Add line number to HitTestPosition

- piet/src/text.rs
A few little fixes to some of the  text doc strings.
> Text doc fixups

- piet-coregraphics/src/ct_helpers.rs
- piet-coregraphics/src/text.rs
This will better match user expectations, and matches the behaviour
on windows.
closes #257
> [cg] Fallback to synthetic italic when italic face is missing

- piet-cairo/src/text.rs
- piet-cairo/src/text/lines.rs
- piet-coregraphics/src/text.rs
- piet-direct2d/src/text.rs
- piet-direct2d/src/text/lines.rs
- piet-svg/src/text.rs
- piet-web/src/text.rs
- piet-web/src/text/lines.rs
- piet/src/color.rs
- piet/src/null_renderer.rs
- piet/src/text.rs
> Remove old deprecation warnings, remove width() impls

- piet-coregraphics/src/text.rs
- piet-direct2d/src/text.rs
- piet/src/samples/picture_10.rs
- piet/src/samples/picture_12.rs
- piet/src/samples/picture_7.rs
- piet/src/samples/picture_8.rs
- piet/src/samples/picture_9.rs
- piet/src/text.rs
- piet/src/util.rs
Size -> FontSize, Font -> FontFamily
> Clarify TextAttribute member names

- piet-direct2d/src/text.rs
> [d2d] Fix vertical measurement discrepancies

- piet-cairo/Cargo.toml
- piet-common/Cargo.toml
- piet-coregraphics/Cargo.toml
- piet-direct2d/Cargo.toml
- piet-svg/Cargo.toml
- piet-web/Cargo.toml
- piet/Cargo.toml
I'd like to get in the `FontStyle` stuff.
> Bump version to 0.2.0-pre2

- piet/src/color.rs
- piet/src/font.rs
> Impl PartialEq for Color, Hash for FontFamily

- piet-cairo/src/text.rs
- piet-coregraphics/src/text.rs
- piet-direct2d/src/text.rs
- piet-svg/src/text.rs
- piet-web/src/text.rs
- piet/src/null_renderer.rs
- piet/src/text.rs
See https://github.com/linebender/piet/issues/298
closes #298
> Remove TextLayout::update_width

- piet-direct2d/src/d2d.rs
- piet-direct2d/src/lib.rs
Working on #309. With this change my time spent in path_from_shape (now also geometry_from_shape) is cut roughly in half.
Note that this currently builds on top of #307. Only the last 2 commits are new. That PR should be merged first, and then this rebased on top of that merge (and then given a fresh CI run), before merging.
> Add shape specialization to d2d geometry generation.

- piet-coregraphics/src/ct_helpers.rs
- piet-coregraphics/src/text.rs
Unlike the other backends, with coretext we were not storing
a Vec<LineMetric> in the layout object, but instead generating
them on demand.
As I work on standardizing the behaviour around newlines at EOF
and treating an empty layout as having a single line, it is easier
to reason about a single source of 'line truth'; the logic started
to get hard to follow in the previous case.
This also cleans up the API in ct_helpers somewhat; much of it
was written before some improvements were upstreamed to the
core-text crate, and we can be less fancy there.
This includes one small change to behaviour: we were previously
storing the floored baseline in the line_y_positions vector,
which I _think_ was hiding a small bug. This may cause subtle
changes to rendering behaviour, which I will correct in …
> [cg] Compute LineMetrics greedily

- piet-common/tests/text.rs
- piet-direct2d/src/text.rs
- fixes #334
- references linebender/druid#1297
> Negative width constraints

- piet-cairo/Cargo.toml
- piet-cairo/src/lib.rs
- piet-common/Cargo.toml
- piet-coregraphics/Cargo.toml
- piet-coregraphics/src/lib.rs
- piet-direct2d/Cargo.toml
- piet-direct2d/src/lib.rs
- piet-svg/Cargo.toml
- piet-svg/src/lib.rs
- piet-web/Cargo.toml
- piet-web/src/lib.rs
- piet/Cargo.toml
Fingers crossed, this will be the last pre-release.
I'd like to at least get #340 and probably #342 in before doing a release, but this gets the paperwork in order.
> Bump version and update dependencies

- piet-cairo/src/text.rs
- piet-common/tests/text.rs
- piet-coregraphics/src/text.rs
- piet-direct2d/src/text.rs
- piet-svg/src/text.rs
- piet-web/src/text.rs
I'm using the CI to check my code on other platforms.
> Add debug impls to text types.

- piet-cairo/src/lib.rs
- piet-coregraphics/src/lib.rs
- piet-direct2d/src/d2d.rs
- piet-direct2d/src/lib.rs
- piet/src/image.rs
- piet/src/render_context.rs
- piet/src/samples/picture_2.rs
This is based off of #350; I'd like to get this landed before the next release, but we should at least get d2d support working.
- closes #350, closes #313
> Finish up grayscale work

- piet-cairo/Cargo.toml
- piet-common/Cargo.toml
- piet-common/src/cairo_back.rs
- piet-common/src/cg_back.rs
- piet-common/src/direct2d_back.rs
- piet-common/src/web_back.rs
- piet-coregraphics/Cargo.toml
- piet-direct2d/Cargo.toml
- piet-svg/Cargo.toml
- piet-web/Cargo.toml
- piet/Cargo.toml
- piet/src/text.rs
Bump crate versions and remove deprecations.
> Prepare for 0.3.0 release

- .github/workflows/ci.yml
- piet-common/Cargo.toml
- piet-common/tests/text.rs
- piet-web/src/text.rs
> Test wasm in ci

- piet-common/Cargo.toml
- piet-web/Cargo.toml
This unbreaks druid-web stuff.
> This updates piet-web and piet-common to v0.3.1

- piet/src/util.rs
`sie` to `size` in line 10 of piet/src/util.rs
> Fix minor typo

- piet/src/conv.rs
- piet/src/image.rs
- piet/src/lib.rs
- piet/src/render_context.rs
While working on #417 I noticed there were a few places where
documentation was missing or rendering poorly.
> Small doc improvements

- piet-common/tests/text.rs
This now uses a monospace font, which will have more predictable
results.
> Fixup trailing_whitespace_width test

- piet-common/tests/text.rs
This will let us these tests from various backends (particularly
cairo)
> Add some hit_test_point tests to piet-common

- piet-common/Cargo.toml
- piet-common/src/direct2d_back.rs
- piet-direct2d/Cargo.toml
- piet-direct2d/examples/test-picture.rs
- piet-direct2d/src/lib.rs
- piet-direct2d/src/text.rs
Progress  on https://github.com/linebender/druid/issues/1622
> [d2d] Easier sharing of fonts between text factory instances

- piet/src/util.rs
> Standardise font size when less than 0

- piet-cairo/Cargo.toml
- piet-common/Cargo.toml
- piet-coregraphics/Cargo.toml
- piet-direct2d/Cargo.toml
- piet-svg/Cargo.toml
- piet-web/Cargo.toml
- piet/Cargo.toml
I think we need a prerelease here so we can check that the GTK4 stuff in
druid works as expected.
> Update manifests for 0.5 prerelease

- piet-cairo/src/text.rs
- piet-coregraphics/src/lib.rs
These fields are now exposed as methods by pango
> Remove pango hack

- piet-common/src/cairo_back.rs
I'm opening this up as a draft for some general fixes and improvements related to `piet-cairo`.
> `piet-cairo` improvements

- piet-cairo/README.md
- piet-common/Cargo.toml
- piet-common/README.md
- piet-common/src/lib.rs
Hello there! 
I was trying to play with Druid on FreeBSD and saw Piet works on OpenBSD so followed #466 everything builds and the example at least works flawlessly 😲 
No changes needed, the Mondrian example `cargo run --example mondrian --features png` generates a beautiful picture.
> Build on FreeBSD.

- .github/workflows/ci.yml
- .github/workflows/snapshot.yml
- piet-cairo/src/lib.rs
- piet-direct2d/src/lib.rs
- piet-direct2d/src/text.rs
- piet-web/src/lib.rs
- piet/src/samples/picture_1.rs
Maybe reopening this will make the CI finish?
> Silence clippy.

- piet-common/src/direct2d_back.rs
> fix: allow drawing after copying raw pixels

- piet-common/src/direct2d_back.rs
- piet-direct2d/src/d2d.rs
#569 solved the issue for the happy path already, but if one of the failure paths of `copy_raw_pixels` would run then the happy path's `begin_draw` method invocation would never happen.
This PR adds a simple `DrawRestarter` that ensures drawing gets restarted as it is dropped when execution returns from `copy_raw_pixels`. Similar to a `finally` section in other languages.
> Add a robust way to temporarily end Direct2D drawing.

- piet-cairo/Cargo.toml
- piet-coregraphics/Cargo.toml
- piet-direct2d/Cargo.toml
- piet-svg/Cargo.toml
- piet/Cargo.toml
These are semver changes, but that don't require changes to the Piet source code.
> Update more deps.

- piet-cairo/Cargo.toml
- piet-common/Cargo.toml
- piet-coregraphics/Cargo.toml
- piet-direct2d/Cargo.toml
- piet-svg/Cargo.toml
- piet-web/Cargo.toml
- piet/Cargo.toml
Increment the version numbers of all the packages.
> Prepare for releasing v0.7.0.
